// Copyright © Erickson Lopez. MIT License.
using System;
using System.Linq;
using System.Reflection;
using AwesomeAssertions;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.SharedKernel.SourceGenerators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using NSubstitute;
using Xunit;

namespace EricksonLopez.SharedKernel.SourceGenerators.Tests;

public class DapperRegistrationGeneratorTests
{
    private static string Normalize(string s) => RoslynTestSyntaxHelper.Normalize(s);

    [Fact]
    public void Generator_RegistersAttributeSource_DuringPostInitialization()
    {
        var runResult = RunGeneratorDriver<DapperRegistrationGenerator>("// empty");

        var attributeTree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("GenerateDapperStrongIdRegistrationsAttribute.g.cs", StringComparison.Ordinal));
        attributeTree.Should().NotBeNull();
        var content = Normalize(attributeTree!.ToString());

        const string expectedAttributeSource = @"// <auto-generated/>
#nullable enable
namespace EricksonLopez.SharedKernel.Dapper
{
    /// <summary>
    /// Instructs the source generator to generate compile-time Native AOT Dapper type handler registrations for all StrongIds in this compilation.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly | global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class GenerateDapperStrongIdRegistrationsAttribute : global::System.Attribute
    {
    }
}";

        content.Should().Be(Normalize(expectedAttributeSource));
    }

    [Fact]
    public void Generator_DiscoversAllStrongIdVariations_GeneratesExactSortedAotRegistrations()
    {
        const string source = @"
using System;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.SharedKernel;

namespace SampleApp;

[StrongId<string>]
public readonly record struct CodeId(string Value);

public readonly record struct DeptId(int Value) : IStrongId<DeptId, int>;
public readonly record struct OrderId(Guid Value) : IStrongId<OrderId, Guid>;
public readonly record struct CustomerId(Guid Value) : IStrongId<CustomerId, Guid>;

public abstract class AbstractId : IStrongId<AbstractId, Guid>;
public class PlainClass { public int Id { get; set; } }
";

        var runResult = RunGeneratorDriver<DapperRegistrationGenerator>(source);

        var regTree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("GeneratedDapperStrongIdRegistryExtensions.g.cs", StringComparison.Ordinal));
        regTree.Should().NotBeNull();
        var output = Normalize(regTree!.ToString());

        const string expectedOutput = @"// <auto-generated/>
#nullable enable

namespace EricksonLopez.SharedKernel.Dapper
{
    /// <summary>
    /// Compile-time generated Native AOT &amp; Trimming safe Dapper StrongId registrations.
    /// </summary>
    public static class GeneratedDapperStrongIdRegistryExtensions
    {
        /// <summary>
        /// Registers all discovered Strongly-Typed IDs with Dapper's SqlMapper without runtime reflection.
        /// </summary>
        public static void RegisterAllGeneratedStrongIds()
        {
            global::EricksonLopez.SharedKernel.Dapper.DapperStrongIdRegistry.Register<global::SampleApp.CodeId, string>();
            global::EricksonLopez.SharedKernel.Dapper.DapperStrongIdRegistry.Register<global::SampleApp.CustomerId, global::System.Guid>();
            global::EricksonLopez.SharedKernel.Dapper.DapperStrongIdRegistry.Register<global::SampleApp.DeptId, int>();
            global::EricksonLopez.SharedKernel.Dapper.DapperStrongIdRegistry.Register<global::SampleApp.OrderId, global::System.Guid>();
        }
    }
}";

        output.Should().Be(Normalize(expectedOutput));
    }

    [Fact]
    public void Generator_WithTypeOfStrongIdAttribute_GeneratesRegistration()
    {
        const string source = @"
using System;
using EricksonLopez.SharedKernel;

namespace SampleApp;

[StrongId(typeof(decimal))]
public readonly record struct PriceId(decimal Value);
";

        var runResult = RunGeneratorDriverWithSharedKernel<DapperRegistrationGenerator>(source);

        var regTree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("GeneratedDapperStrongIdRegistryExtensions.g.cs", StringComparison.Ordinal));
        regTree.Should().NotBeNull();
        var output = Normalize(regTree!.ToString());

        output.Should().Contain("global::EricksonLopez.SharedKernel.Dapper.DapperStrongIdRegistry.Register<global::SampleApp.PriceId, decimal>();");
    }

    [Fact]
    public void Generator_WithMultipleAttributesAndInterfaces_FirstWins()
    {
        const string source = @"
using System;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.SharedKernel;

namespace SampleApp;

[StrongId<Guid>]
[StrongId<int>]
public readonly record struct MultiAttrId(Guid Value);

[StrongId(typeof(Guid))]
[StrongId(typeof(int))]
public readonly record struct MultiTypeofId(Guid Value);

public readonly record struct MultiIfaceId(Guid Value) : IStrongId<MultiIfaceId, Guid>, IDisposable
{
    public void Dispose() { }
}
";

        var runResult = RunGeneratorDriverWithSharedKernel<DapperRegistrationGenerator>(source);

        var regTree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("GeneratedDapperStrongIdRegistryExtensions.g.cs", StringComparison.Ordinal));
        regTree.Should().NotBeNull();
        var output = Normalize(regTree!.ToString());

        output.Should().Contain("Register<global::SampleApp.MultiAttrId, global::System.Guid>();");
        output.Should().Contain("Register<global::SampleApp.MultiTypeofId, global::System.Guid>();");
        output.Should().Contain("Register<global::SampleApp.MultiIfaceId, global::System.Guid>();");
    }

    [Fact]
    public void Generator_WithStrongIdWithoutAttributeSuffix_GeneratesRegistration()
    {
        const string source = @"
using System;

namespace CustomAttrs
{
    [AttributeUsage(AttributeTargets.Struct)]
    public class StrongId<T> : Attribute { }

    [AttributeUsage(AttributeTargets.Struct)]
    public class StrongId : Attribute
    {
        public Type ValueType { get; }
        public StrongId(Type type) => ValueType = type;
    }
}

namespace SampleApp
{
    using CustomAttrs;

    [StrongId<Guid>]
    public readonly record struct CustomSuffixGenericId(Guid Value);

    [StrongId(typeof(int))]
    public readonly record struct CustomSuffixNonGenericId(int Value);
}
";

        var runResult = RunGeneratorDriver<DapperRegistrationGenerator>(source);

        var regTree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("GeneratedDapperStrongIdRegistryExtensions.g.cs", StringComparison.Ordinal));
        regTree.Should().NotBeNull();
        var output = Normalize(regTree!.ToString());

        output.Should().Contain("Register<global::SampleApp.CustomSuffixGenericId, global::System.Guid>();");
        output.Should().Contain("Register<global::SampleApp.CustomSuffixNonGenericId, int>();");
    }

    [Fact]
    public void Generator_WithNonMatchingInterfacesAndAttributes_SkipsNonMatches()
    {
        const string source = @"
using System;

namespace EricksonLopez.SharedKernel
{
    [AttributeUsage(AttributeTargets.Struct)]
    public class StrongId<T1, T2> : Attribute { }
}

namespace SampleApp
{
    using EricksonLopez.SharedKernel;

    public interface IOtherInterface<T1, T2> { }
    public interface IStrongId<T> { }
    public class FakeAttribute<T1, T2> : Attribute { }

    [Fake<int, string>]
    public class ClassWithTwoArgAttribute { }

    [StrongId<int, string>]
    public class ClassWithTwoArgStrongId { }

    public class ClassWithOtherInterface : IOtherInterface<int, string> { }

    public class ClassWithOneArgInterface : IStrongId<int> { }
}
";

        var runResult = RunGeneratorDriver<DapperRegistrationGenerator>(source);

        var regTree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("GeneratedDapperStrongIdRegistryExtensions.g.cs", StringComparison.Ordinal));
        regTree.Should().BeNull();
    }

    [Fact]
    public void Generator_WhenNoStrongIds_DoesNotGenerateRegistrationCode()
    {
        const string source = @"
using System;

namespace SampleApp;

public class PlainClass
{
    public int Id { get; set; }
}
";

        var runResult = RunGeneratorDriver<DapperRegistrationGenerator>(source);

        var regTree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("GeneratedDapperStrongIdRegistryExtensions.g.cs", StringComparison.Ordinal));
        regTree.Should().BeNull();
    }

    [Fact]
    public void Generator_WithNestedStrongIdTypes_GeneratesFullyQualifiedRegistrations()
    {
        const string source = @"
using System;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.SharedKernel;

namespace SampleApp
{
    public static class OuterContainer
    {
        public readonly record struct NestedOrderId(Guid Value) : IStrongId<NestedOrderId, Guid>;

        public static class DeepContainer
        {
            [StrongId<long>]
            public readonly record struct DeepNestedId(long Value);
        }
    }
}
";

        var runResult = RunGeneratorDriver<DapperRegistrationGenerator>(source);

        var regTree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("GeneratedDapperStrongIdRegistryExtensions.g.cs", StringComparison.Ordinal));
        regTree.Should().NotBeNull();
        var output = Normalize(regTree!.ToString());

        output.Should().Contain("Register<global::SampleApp.OuterContainer.DeepContainer.DeepNestedId, long>();");
        output.Should().Contain("Register<global::SampleApp.OuterContainer.NestedOrderId, global::System.Guid>();");
    }

    [Fact]
    public void GetStrongIdTypeInfo_WhenDeclaredSymbolIsNull_ReturnsNull()
    {
        var method = typeof(DapperRegistrationGenerator).GetMethod("GetStrongIdTypeInfo", BindingFlags.NonPublic | BindingFlags.Static);
        method.Should().NotBeNull();

        var tree = CSharpSyntaxTree.ParseText("public class Sample { }");
        var node = tree.GetRoot().DescendantNodes().OfType<TypeDeclarationSyntax>().First();

        var semanticModel = Substitute.For<SemanticModel>();
        semanticModel.GetDeclaredSymbol(Arg.Any<SyntaxNode>(), Arg.Any<System.Threading.CancellationToken>()).Returns((ISymbol?)null);

        var contextType = typeof(GeneratorSyntaxContext);
        var ctor = contextType.GetConstructors(BindingFlags.NonPublic | BindingFlags.Instance).First();
        var context = ctor.Invoke(new object[] { node, new Lazy<SemanticModel>(() => semanticModel), null! });

        var result = method!.Invoke(null, new object[] { context, System.Threading.CancellationToken.None });
        result.Should().BeNull();
    }

    [Fact]
    public void DapperStrongIdItem_EqualityAndHashCode_WorkCorrectly()
    {
        var itemType = typeof(DapperRegistrationGenerator).Assembly
            .GetType("EricksonLopez.SharedKernel.SourceGenerators.DapperRegistrationGenerator+DapperStrongIdItem");

        itemType.Should().NotBeNull();

        var item1 = Activator.CreateInstance(itemType!, "global::App.Id1", "global::System.Guid");
        var item2 = Activator.CreateInstance(itemType!, "global::App.Id1", "global::System.Guid");
        var item3 = Activator.CreateInstance(itemType!, "global::App.Id2", "int");
        var item4 = Activator.CreateInstance(itemType!, "global::App.Id1", "int");

        item1.Should().Be(item2);
        item1.Should().NotBe(item3);
        item1.Should().NotBe(item4);
        item1.Should().NotBe(null);
        item1.Should().NotBe(new object());
        item1!.GetHashCode().Should().Be(item2!.GetHashCode());
    }

    private static GeneratorDriverRunResult RunGeneratorDriver<TGenerator>(string source)
        where TGenerator : IIncrementalGenerator, new()
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source);
        var references = new MetadataReference[]
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Attribute).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(IStrongId<,>).Assembly.Location),
        };

        var compilation = CSharpCompilation.Create(
            "TestCompilation",
            new[] { syntaxTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new TGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out _, out var diagnostics);
        diagnostics.Should().NotContain(d => d.Severity == DiagnosticSeverity.Error);

        return driver.GetRunResult();
    }

    private static GeneratorDriverRunResult RunGeneratorDriverWithSharedKernel<TGenerator>(string source)
        where TGenerator : IIncrementalGenerator, new()
    {
        const string attributeSource = @"
namespace EricksonLopez.SharedKernel
{
    [System.AttributeUsage(System.AttributeTargets.Struct | System.AttributeTargets.Class)]
    public sealed class StrongIdAttribute : System.Attribute
    {
        public System.Type ValueType { get; }
        public StrongIdAttribute(System.Type valueType) => ValueType = valueType;
    }
}
";
        var syntaxTree = CSharpSyntaxTree.ParseText(source);
        var attrTree = CSharpSyntaxTree.ParseText(attributeSource);
        var references = new MetadataReference[]
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Attribute).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(IStrongId<,>).Assembly.Location),
        };

        var compilation = CSharpCompilation.Create(
            "TestCompilation",
            new[] { syntaxTree, attrTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new TGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out _, out var diagnostics);
        diagnostics.Should().NotContain(d => d.Severity == DiagnosticSeverity.Error);

        return driver.GetRunResult();
    }
}
