// Copyright © Erickson Lopez. MIT License.

namespace EricksonLopez.SharedKernel.SourceGenerators.Tests;

using System;
using System.Collections.Generic;
using System.Linq;
using AwesomeAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

public sealed class MetadataSourceGeneratorTests
{
    private static string Normalize(string s) => RoslynTestSyntaxHelper.Normalize(s);

    [Fact]
    public void Generator_WhenNoEntitiesPresent_EmitsNoSource()
    {
        const string source = @"
namespace TestApp
{
    public class PlainPoco
    {
        public int Id { get; set; }
    }
}";
        var runResult = RunGenerator(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().BeNull();
    }

    [Fact]
    public void Generator_WhenEntitySubclass_EmitsMetadataRegistry()
    {
        const string source = @"
using System;
using EricksonLopez.SharedKernel.Persistence;

namespace TestApp
{
    public class Order : EricksonLopez.SharedKernel.Entity
    {
        public Guid Id { get; set; }

        public Guid TenantId { get; set; }

        public DateTimeOffset CreatedAt { get; set; }

        public decimal Total { get; set; }
    }
}";
        var runResult = RunGenerator(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().NotBeNull();
        var code = generatedTree!.ToString();

        code.Should().Contain("namespace EricksonLopez.SharedKernel.Persistence.Generated;");
        code.Should().Contain("public static class GeneratedMetadataRegistry");
        code.Should().Contain("TableName = \"Order\"");
        code.Should().Contain("Schema = \"public\"");
        code.Should().Contain("ColumnName: \"Id\"");
        code.Should().Contain("IsKey: true");
        code.Should().Contain("IsTenantColumn: true");
        code.Should().Contain("PrimaryKeys = columns_TestApp_Order.Where(c => c.IsKey).ToList()");
        code.Should().Contain("TenantColumn = columns_TestApp_Order.FirstOrDefault(c => c.IsTenantColumn)");
    }

    [Fact]
    public void Generator_WithSoftDeleteAndConcurrencyToken_EmitsSpecializedColumnsAndDefensiveSetters()
    {
        const string source = @"
using System;
using EricksonLopez.SharedKernel.Persistence;

namespace TestApp
{
    public class Product : EricksonLopez.SharedKernel.Entity
    {
        public Guid Id { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] RowVersion { get; set; }
        public string Name { get; set; }
    }
}";
        var runResult = RunGenerator(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().NotBeNull();
        var code = generatedTree!.ToString();

        code.Should().Contain("IsSoftDeleteColumn: true");
        code.Should().Contain("IsConcurrencyToken: true");
        code.Should().Contain("SoftDeleteColumn = columns_TestApp_Product.FirstOrDefault(c => c.IsSoftDeleteColumn)");
        code.Should().Contain("ConcurrencyToken = columns_TestApp_Product.FirstOrDefault(c => c.IsConcurrencyToken)");
        code.Should().Contain("throw new global::System.ArgumentNullException");
    }

    [Fact]
    public void Generator_WithExactEmittedSource_MatchesNormalizedOutput()
    {
        const string source = @"
using System;

namespace TestApp
{
    public class SimpleOrder : EricksonLopez.SharedKernel.Entity
    {
        public Guid Id { get; set; }
        public string? Description { get; set; }
        public int ReadOnlyCode { get; }
    }
}";
        var runResult = RunGenerator(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().NotBeNull();
        var output = Normalize(generatedTree!.ToString());

        const string expectedExact = @"// <auto-generated/>
#nullable enable
#pragma warning disable CS0618
using System;
using System.Collections.Generic;
using System.Linq;
using EricksonLopez.SharedKernel.Persistence;

namespace EricksonLopez.SharedKernel.Persistence.Generated;

/// <summary>
/// Compile-time generated metadata registry for domain entities.
/// </summary>
public static class GeneratedMetadataRegistry
{
    /// <summary>
    /// Returns the complete enumeration of compiled entity metadata descriptors.
    /// </summary>
    public static IEnumerable<EntityMetadata> GetAllRawMetadata()
    {

        // ── TestApp.SimpleOrder ──
        var columns_TestApp_SimpleOrder = new List<PropertyMetadata>();
        columns_TestApp_SimpleOrder.Add(new PropertyMetadata(
            ClrName: ""Id"",
            ClrType: typeof(global::System.Guid),
            ColumnName: ""Id"",
            DatabaseType: string.Empty,
            IsKey: true,
            IsNullable: false,
            IsAuditColumn: false,
            IsSoftDeleteColumn: false,
            IsTenantColumn: false,
            IsConcurrencyToken: false,
            Getter: (object obj) => (object?)((global::TestApp.SimpleOrder)obj).Id,
            Setter: (object obj, object? val) => ((global::TestApp.SimpleOrder)obj).Id = val is null ? throw new global::System.ArgumentNullException(nameof(val), ""Cannot assign null to non-nullable property 'Id' on 'global::TestApp.SimpleOrder'."") : (global::System.Guid)val));
        columns_TestApp_SimpleOrder.Add(new PropertyMetadata(
            ClrName: ""Description"",
            ClrType: typeof(string),
            ColumnName: ""Description"",
            DatabaseType: string.Empty,
            IsKey: false,
            IsNullable: true,
            IsAuditColumn: false,
            IsSoftDeleteColumn: false,
            IsTenantColumn: false,
            IsConcurrencyToken: false,
            Getter: (object obj) => (object?)((global::TestApp.SimpleOrder)obj).Description,
            Setter: (object obj, object? val) => ((global::TestApp.SimpleOrder)obj).Description = val is null ? default! : (string)val));
        columns_TestApp_SimpleOrder.Add(new PropertyMetadata(
            ClrName: ""ReadOnlyCode"",
            ClrType: typeof(int),
            ColumnName: ""ReadOnlyCode"",
            DatabaseType: string.Empty,
            IsKey: false,
            IsNullable: false,
            IsAuditColumn: false,
            IsSoftDeleteColumn: false,
            IsTenantColumn: false,
            IsConcurrencyToken: false,
            Getter: (object obj) => (object?)((global::TestApp.SimpleOrder)obj).ReadOnlyCode,
            Setter: null));
        yield return new EntityMetadata
        {
            ClrType = typeof(global::TestApp.SimpleOrder),
            TableName = ""SimpleOrder"",
            Schema = ""public"",
            Columns = columns_TestApp_SimpleOrder,
            PrimaryKeys = columns_TestApp_SimpleOrder.Where(c => c.IsKey).ToList(),
            TenantColumn = columns_TestApp_SimpleOrder.FirstOrDefault(c => c.IsTenantColumn),
            SoftDeleteColumn = columns_TestApp_SimpleOrder.FirstOrDefault(c => c.IsSoftDeleteColumn),
            ConcurrencyToken = columns_TestApp_SimpleOrder.FirstOrDefault(c => c.IsConcurrencyToken)
        };
    }
}";

        output.Should().Be(Normalize(expectedExact));
    }

    [Fact]
    public void Generator_WhenCandidateIsAggregateRoot_EmitsMetadata()
    {
        const string source = @"
using System;

namespace TestApp
{
    public class OrderAggregate : EricksonLopez.SharedKernel.AggregateRoot
    {
        public Guid Id { get; set; }
    }
}";
        var runResult = RunGenerator(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().NotBeNull();
        generatedTree!.ToString().Should().Contain("TableName = \"OrderAggregate\"");
    }

    [Fact]
    public void Generator_WhenCandidateImplementsIAggregateRootOrIEntity_EmitsMetadata()
    {
        const string source = @"
using System;

namespace TestApp
{
    public class DirectAggregate : EricksonLopez.SharedKernel.IAggregateRoot
    {
        public Guid Id { get; set; }
    }

    public class DirectEntity : EricksonLopez.SharedKernel.IEntity
    {
        public Guid Id { get; set; }
    }
}";
        var runResult = RunGenerator(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().NotBeNull();
        var code = generatedTree!.ToString();
        code.Should().Contain("TableName = \"DirectAggregate\"");
        code.Should().Contain("TableName = \"DirectEntity\"");
    }

    [Fact]
    public void Generator_WhenCandidateIsAbstractOrWrongNamespace_DoesNotEmitMetadata()
    {
        const string source = @"
using System;

namespace OtherNs
{
    public abstract class Entity { }
    public interface IEntity { }
}

namespace TestApp
{
    public abstract class AbstractOrder : EricksonLopez.SharedKernel.Entity
    {
        public Guid Id { get; set; }
    }

    public class ForeignEntity : OtherNs.Entity
    {
        public Guid Id { get; set; }
    }

    public class ForeignIfaceEntity : OtherNs.IEntity
    {
        public Guid Id { get; set; }
    }
}";
        var runResult = RunGenerator(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().BeNull();
    }

    [Fact]
    public void Generator_WhenCompilationLacksPersistenceMetadata_EmitsNoSource()
    {
        const string source = @"
using System;

namespace TestApp
{
    public class Order : EricksonLopez.SharedKernel.Entity
    {
        public Guid Id { get; set; }
    }
}";
        var runResult = RunGeneratorWithoutPersistence(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().BeNull();
    }

    [Fact]
    public void Generator_WithPropertyKeyAttributes_DetectsAllKeyVariations()
    {
        const string source = @"
using System;
using System.ComponentModel.DataAnnotations;
using CustomAttrs;

namespace TestApp
{
    public class KeyModel : EricksonLopez.SharedKernel.Entity
    {
        public Guid Id { get; set; }
        [KeyAttribute] public string AttrKey { get; set; }
        [Key] public string ShortKey { get; set; }
        public string PlainCode { get; set; }
    }
}";
        var runResult = RunGenerator(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().NotBeNull();
        var code = Normalize(generatedTree!.ToString());

        code.Should().Contain("ClrName: \"Id\",\n            ClrType: typeof(global::System.Guid),\n            ColumnName: \"Id\",\n            DatabaseType: string.Empty,\n            IsKey: true,");
        code.Should().Contain("ClrName: \"AttrKey\",\n            ClrType: typeof(string),\n            ColumnName: \"AttrKey\",\n            DatabaseType: string.Empty,\n            IsKey: true,");
        code.Should().Contain("ClrName: \"ShortKey\",\n            ClrType: typeof(string),\n            ColumnName: \"ShortKey\",\n            DatabaseType: string.Empty,\n            IsKey: true,");
        code.Should().Contain("ClrName: \"PlainCode\",\n            ClrType: typeof(string),\n            ColumnName: \"PlainCode\",\n            DatabaseType: string.Empty,\n            IsKey: false,");
    }

    [Fact]
    public void Generator_WithPropertyTenantAttributesAndNames_DetectsAllTenantVariations()
    {
        const string source = @"
using System;
using EricksonLopez.SharedKernel.Persistence;
using CustomAttrs;

namespace TestApp
{
    public class TenantModel : EricksonLopez.SharedKernel.Entity
    {
        public Guid Id { get; set; }
        public Guid TenantId { get; set; }
        public Guid CompanyId { get; set; }
        [TenantIdAttribute] public Guid AttrTenant { get; set; }
        [TenantId] public Guid ShortTenant { get; set; }
        public Guid NormalCol { get; set; }
    }
}";
        var runResult = RunGenerator(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().NotBeNull();
        var code = Normalize(generatedTree!.ToString());

        code.Should().Contain("ClrName: \"TenantId\",\n            ClrType: typeof(global::System.Guid),\n            ColumnName: \"TenantId\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: true,");
        code.Should().Contain("ClrName: \"CompanyId\",\n            ClrType: typeof(global::System.Guid),\n            ColumnName: \"CompanyId\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: true,");
        code.Should().Contain("ClrName: \"AttrTenant\",\n            ClrType: typeof(global::System.Guid),\n            ColumnName: \"AttrTenant\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: true,");
        code.Should().Contain("ClrName: \"ShortTenant\",\n            ClrType: typeof(global::System.Guid),\n            ColumnName: \"ShortTenant\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: true,");
        code.Should().Contain("ClrName: \"NormalCol\",\n            ClrType: typeof(global::System.Guid),\n            ColumnName: \"NormalCol\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: false,");
    }

    [Fact]
    public void Generator_WithPropertySoftDeleteAttributesAndNames_DetectsAllSoftDeleteVariations()
    {
        const string source = @"
using System;
using EricksonLopez.SharedKernel.Persistence;
using CustomAttrs;

namespace TestApp
{
    public class SoftDeleteModel : EricksonLopez.SharedKernel.Entity
    {
        public Guid Id { get; set; }
        public bool IsDeleted { get; set; }
        public bool Deleted { get; set; }
        public bool IsArchived { get; set; }
        [SoftDeleteAttribute] public bool AttrDeleted { get; set; }
        [SoftDelete] public bool ShortDeleted { get; set; }
        public bool NormalActive { get; set; }
    }
}";
        var runResult = RunGenerator(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().NotBeNull();
        var code = Normalize(generatedTree!.ToString());

        code.Should().Contain("ClrName: \"IsDeleted\",\n            ClrType: typeof(bool),\n            ColumnName: \"IsDeleted\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: true,");
        code.Should().Contain("ClrName: \"Deleted\",\n            ClrType: typeof(bool),\n            ColumnName: \"Deleted\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: true,");
        code.Should().Contain("ClrName: \"IsArchived\",\n            ClrType: typeof(bool),\n            ColumnName: \"IsArchived\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: true,");
        code.Should().Contain("ClrName: \"AttrDeleted\",\n            ClrType: typeof(bool),\n            ColumnName: \"AttrDeleted\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: true,");
        code.Should().Contain("ClrName: \"ShortDeleted\",\n            ClrType: typeof(bool),\n            ColumnName: \"ShortDeleted\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: true,");
        code.Should().Contain("ClrName: \"NormalActive\",\n            ClrType: typeof(bool),\n            ColumnName: \"NormalActive\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,");
    }

    [Fact]
    public void Generator_WithPropertyConcurrencyAttributesAndNames_DetectsAllConcurrencyVariations()
    {
        const string source = @"
using System;
using System.ComponentModel.DataAnnotations;
using CustomAttrs;

namespace TestApp
{
    public class ConcurrencyModel : EricksonLopez.SharedKernel.Entity
    {
        public Guid Id { get; set; }
        public int Version { get; set; }
        public byte[] RowVersion { get; set; }
        public uint xmin { get; set; }
        [TimestampAttribute] public byte[] Token1 { get; set; }
        [Timestamp] public byte[] Token2 { get; set; }
        [ConcurrencyCheckAttribute] public string Token3 { get; set; }
        [ConcurrencyCheck] public string Token4 { get; set; }
        public string PlainDesc { get; set; }
    }
}";
        var runResult = RunGenerator(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().NotBeNull();
        var code = Normalize(generatedTree!.ToString());

        code.Should().Contain("ClrName: \"Version\",\n            ClrType: typeof(int),\n            ColumnName: \"Version\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: false,\n            IsConcurrencyToken: true,");
        code.Should().Contain("ClrName: \"RowVersion\",\n            ClrType: typeof(byte[]),\n            ColumnName: \"RowVersion\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: false,\n            IsConcurrencyToken: true,");
        code.Should().Contain("ClrName: \"xmin\",\n            ClrType: typeof(uint),\n            ColumnName: \"xmin\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: false,\n            IsConcurrencyToken: true,");
        code.Should().Contain("ClrName: \"Token1\",\n            ClrType: typeof(byte[]),\n            ColumnName: \"Token1\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: false,\n            IsConcurrencyToken: true,");
        code.Should().Contain("ClrName: \"Token2\",\n            ClrType: typeof(byte[]),\n            ColumnName: \"Token2\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: false,\n            IsConcurrencyToken: true,");
        code.Should().Contain("ClrName: \"Token3\",\n            ClrType: typeof(string),\n            ColumnName: \"Token3\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: false,\n            IsConcurrencyToken: true,");
        code.Should().Contain("ClrName: \"Token4\",\n            ClrType: typeof(string),\n            ColumnName: \"Token4\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: false,\n            IsConcurrencyToken: true,");
        code.Should().Contain("ClrName: \"PlainDesc\",\n            ClrType: typeof(string),\n            ColumnName: \"PlainDesc\",\n            DatabaseType: string.Empty,\n            IsKey: false,\n            IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: false,\n            IsConcurrencyToken: false,");
    }

    [Fact]
    public void Generator_WithPropertyNullabilityAndSetters_EmitsCorrectSetters()
    {
        const string source = @"
using System;

namespace TestApp
{
    public class SetterModel : EricksonLopez.SharedKernel.Entity
    {
        public Guid Id { get; set; }
        public string? NullableRef { get; set; }
        public int? NullableVal { get; set; }
        public string NonNullableRef { get; set; }
        public int NonNullableVal { get; set; }
        public string PublicSet { get; set; }
        public string InternalSet { get; internal set; }
        public string InitOnly { get; init; }
        public string PrivateSet { get; private set; }
        public string ProtectedSet { get; protected set; }
        public string GetterOnly => ""constant"";
    }
}";
        var runResult = RunGenerator(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().NotBeNull();
        var code = Normalize(generatedTree!.ToString());

        code.Should().Contain("IsNullable: true,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: false,\n            IsConcurrencyToken: false,\n            Getter: (object obj) => (object?)((global::TestApp.SetterModel)obj).NullableRef,\n            Setter: (object obj, object? val) => ((global::TestApp.SetterModel)obj).NullableRef = val is null ? default! : (string)val));");
        code.Should().Contain("IsNullable: true,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: false,\n            IsConcurrencyToken: false,\n            Getter: (object obj) => (object?)((global::TestApp.SetterModel)obj).NullableVal,\n            Setter: (object obj, object? val) => ((global::TestApp.SetterModel)obj).NullableVal = val is null ? default! : (int?)val));");
        code.Should().Contain("IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: false,\n            IsConcurrencyToken: false,\n            Getter: (object obj) => (object?)((global::TestApp.SetterModel)obj).NonNullableRef,\n            Setter: (object obj, object? val) => ((global::TestApp.SetterModel)obj).NonNullableRef = val is null ? throw new global::System.ArgumentNullException(nameof(val), \"Cannot assign null to non-nullable property 'NonNullableRef' on 'global::TestApp.SetterModel'.\") : (string)val));");
        code.Should().Contain("IsNullable: false,\n            IsAuditColumn: false,\n            IsSoftDeleteColumn: false,\n            IsTenantColumn: false,\n            IsConcurrencyToken: false,\n            Getter: (object obj) => (object?)((global::TestApp.SetterModel)obj).NonNullableVal,\n            Setter: (object obj, object? val) => ((global::TestApp.SetterModel)obj).NonNullableVal = val is null ? throw new global::System.ArgumentNullException(nameof(val), \"Cannot assign null to non-nullable property 'NonNullableVal' on 'global::TestApp.SetterModel'.\") : (int)val));");
        code.Should().Contain("Getter: (object obj) => (object?)((global::TestApp.SetterModel)obj).InternalSet,\n            Setter: (object obj, object? val) => ((global::TestApp.SetterModel)obj).InternalSet = val is null ? throw new global::System.ArgumentNullException(nameof(val), \"Cannot assign null to non-nullable property 'InternalSet' on 'global::TestApp.SetterModel'.\") : (string)val));");
        code.Should().Contain("Getter: (object obj) => (object?)((global::TestApp.SetterModel)obj).InitOnly,\n            Setter: null));");
        code.Should().Contain("Getter: (object obj) => (object?)((global::TestApp.SetterModel)obj).PrivateSet,\n            Setter: null));");
        code.Should().Contain("Getter: (object obj) => (object?)((global::TestApp.SetterModel)obj).ProtectedSet,\n            Setter: null));");
        code.Should().Contain("Getter: (object obj) => (object?)((global::TestApp.SetterModel)obj).GetterOnly,\n            Setter: null));");
    }

    [Fact]
    public void Generator_WithExcludedPropertiesAndCollections_SkipsExcludedMembers()
    {
        const string source = @"
using System;
using System.Collections;
using System.Collections.Generic;

namespace TestApp
{
    public class ExcludedModel : EricksonLopez.SharedKernel.Entity
    {
        public Guid Id { get; set; }
        public string DomainEvents { get; set; }
        public List<string> ListCol { get; set; }
        public IReadOnlyList<string> ReadOnlyListCol { get; set; }
        public IEnumerable<string> EnumerableCol { get; set; }
        public HashSet<string> SetCol { get; set; }
        public ArrayList ArrayCol { get; set; }
        public static int StaticProp { get; set; }
        public string this[int index] => string.Empty;
        private string PrivateProp { get; set; }
    }
}";
        var runResult = RunGenerator(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().NotBeNull();
        var code = generatedTree!.ToString();

        code.Should().Contain("ClrName: \"Id\"");
        code.Should().NotContain("ClrName: \"DomainEvents\"");
        code.Should().NotContain("ClrName: \"ListCol\"");
        code.Should().NotContain("ClrName: \"ReadOnlyListCol\"");
        code.Should().NotContain("ClrName: \"EnumerableCol\"");
        code.Should().NotContain("ClrName: \"SetCol\"");
        code.Should().NotContain("ClrName: \"ArrayCol\"");
        code.Should().NotContain("ClrName: \"StaticProp\"");
        code.Should().NotContain("ClrName: \"PrivateProp\"");
    }

    [Fact]
    public void Generator_WithMultipleEntities_EmitsSortedDistinctEntities()
    {
        const string source = @"
using System;

namespace TestApp
{
    public class ZebraEntity : EricksonLopez.SharedKernel.Entity
    {
        public Guid Id { get; set; }
    }

    public class AlphaEntity : EricksonLopez.SharedKernel.Entity
    {
        public Guid Id { get; set; }
    }
}";
        var runResult = RunGenerator(source);

        var generatedTree = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.EndsWith("GeneratedMetadataRegistry.g.cs", StringComparison.Ordinal));

        generatedTree.Should().NotBeNull();
        var code = generatedTree!.ToString();

        var alphaIndex = code.IndexOf("TableName = \"AlphaEntity\"", StringComparison.Ordinal);
        var zebraIndex = code.IndexOf("TableName = \"ZebraEntity\"", StringComparison.Ordinal);

        alphaIndex.Should().BeGreaterThan(0);
        zebraIndex.Should().BeGreaterThan(0);
        alphaIndex.Should().BeLessThan(zebraIndex);
    }

    private static GeneratorDriverRunResult RunGenerator(string source)
    {
        const string persistenceAttributesSource = @"
namespace EricksonLopez.SharedKernel
{
    public abstract class Entity { }
    public abstract class AggregateRoot { }
    public interface IEntity { }
    public interface IAggregateRoot { }
}

namespace System.ComponentModel.DataAnnotations
{
    using System;
    [AttributeUsage(AttributeTargets.Property)]
    public class KeyAttribute : Attribute { }

    [AttributeUsage(AttributeTargets.Property)]
    public class TimestampAttribute : Attribute { }

    [AttributeUsage(AttributeTargets.Property)]
    public class ConcurrencyCheckAttribute : Attribute { }
}

namespace EricksonLopez.SharedKernel.Persistence
{
    using System;

    public enum AuditFieldType { CreatedAt, CreatedBy, UpdatedAt, UpdatedBy, Version }

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
    public sealed class TableAttribute : Attribute
    {
        public TableAttribute(string name) => Name = name;
        public string Name { get; }
        public string? Schema { get; set; }
    }

    [AttributeUsage(AttributeTargets.Property)]
    public sealed class ColumnAttribute : Attribute
    {
        public ColumnAttribute(string name) => Name = name;
        public string Name { get; }
        public bool IsPrimaryKey { get; set; }
        public bool IsDatabaseGenerated { get; set; }
    }

    [AttributeUsage(AttributeTargets.Property)]
    public sealed class AuditAttribute : Attribute
    {
        public AuditAttribute(AuditFieldType fieldType) => FieldType = fieldType;
        public AuditFieldType FieldType { get; }
    }

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
    public sealed class TenantScopedAttribute : Attribute {}

    [AttributeUsage(AttributeTargets.Property)]
    public sealed class TenantIdAttribute : Attribute {}

    [AttributeUsage(AttributeTargets.Property)]
    public sealed class SoftDeleteAttribute : Attribute {}

    public sealed record PropertyMetadata(
        string ClrName, Type ClrType, string ColumnName, string DatabaseType,
        bool IsKey, bool IsNullable, bool IsAuditColumn, bool IsSoftDeleteColumn,
        bool IsTenantColumn, bool IsConcurrencyToken,
        Func<object, object?> Getter, Action<object, object?>? Setter);

    public sealed record EntityMetadata
    {
        public Type ClrType { get; init; } = null!;
        public string TableName { get; init; } = string.Empty;
        public string Schema { get; init; } = string.Empty;
        public System.Collections.Generic.IReadOnlyList<PropertyMetadata> Columns { get; init; } = [];
        public System.Collections.Generic.IReadOnlyList<PropertyMetadata> PrimaryKeys { get; init; } = [];
        public PropertyMetadata? TenantColumn { get; init; }
        public PropertyMetadata? SoftDeleteColumn { get; init; }
        public PropertyMetadata? ConcurrencyToken { get; init; }
    }
}

namespace CustomAttrs
{
    using System;
    [AttributeUsage(AttributeTargets.Property)]
    public class Key : Attribute { }

    [AttributeUsage(AttributeTargets.Property)]
    public class TenantId : Attribute { }

    [AttributeUsage(AttributeTargets.Property)]
    public class SoftDelete : Attribute { }

    [AttributeUsage(AttributeTargets.Property)]
    public class Timestamp : Attribute { }

    [AttributeUsage(AttributeTargets.Property)]
    public class ConcurrencyCheck : Attribute { }
}";

        var syntaxTree = CSharpSyntaxTree.ParseText(source);
        var attrTree = CSharpSyntaxTree.ParseText(persistenceAttributesSource);
        var references = new MetadataReference[]
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Attribute).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(DateTimeOffset).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Guid).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(System.Linq.Enumerable).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(System.Collections.ArrayList).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(System.Collections.Generic.List<>).Assembly.Location),
        };

        var compilation = CSharpCompilation.Create(
            "TestCompilation",
            new[] { syntaxTree, attrTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new MetadataSourceGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out _, out var diagnostics);
        diagnostics.Should().NotContain(d => d.Severity == DiagnosticSeverity.Error);

        return driver.GetRunResult();
    }

    private static GeneratorDriverRunResult RunGeneratorWithoutPersistence(string source)
    {
        const string sharedKernelWithoutPersistenceSource = @"
namespace EricksonLopez.SharedKernel
{
    public abstract class Entity { }
}";
        var syntaxTree = CSharpSyntaxTree.ParseText(source);
        var skTree = CSharpSyntaxTree.ParseText(sharedKernelWithoutPersistenceSource);
        var references = new MetadataReference[]
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Attribute).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Guid).Assembly.Location)
        };

        var compilation = CSharpCompilation.Create(
            "TestCompilationNoPersistence",
            new[] { syntaxTree, skTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new MetadataSourceGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out _, out var diagnostics);
        diagnostics.Should().NotContain(d => d.Severity == DiagnosticSeverity.Error);

        return driver.GetRunResult();
    }
}
