// Copyright © Erickson Lopez. MIT License.
using System;
using System.Linq;
using System.Reflection;
using AwesomeAssertions;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.SharedKernel.SourceGenerators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using NSubstitute;
using Xunit;

namespace EricksonLopez.SharedKernel.SourceGenerators.Tests;

public class StrongIdGeneratorTests
{
    private static string Normalize(string s) => RoslynTestSyntaxHelper.Normalize(s);

    [Fact]
    public void Generator_RegistersAttributeSource_DuringPostInitialization()
    {
        var runResult = RunGeneratorDriver<StrongIdGenerator>("// empty");

        var attributeTree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("StrongIdAttribute.g.cs", StringComparison.Ordinal));
        attributeTree.Should().NotBeNull();
        var content = Normalize(attributeTree!.ToString());

        const string expectedAttributeSource = @"// <auto-generated/>
#nullable enable
namespace EricksonLopez.SharedKernel
{
    /// <summary>
    /// Marks a type as a strongly-typed identifier to generate factory methods, operators, and formatting.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class StrongIdAttribute : global::System.Attribute
    {
        public global::System.Type ValueType { get; }

        public StrongIdAttribute(global::System.Type valueType)
        {
            ValueType = valueType;
        }
    }

    /// <summary>
    /// Generic attribute to mark a type as a strongly-typed identifier with underlying type <typeparamref name=""TValue""/>.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class StrongIdAttribute<TValue> : global::System.Attribute
        where TValue : notnull, global::System.IEquatable<TValue>
    {
    }
}";

        content.Should().Be(Normalize(expectedAttributeSource));
    }

    [Fact]
    public void Generator_WithGenericStrongIdAttribute_AndGuidUnderlyingType_GeneratesCompleteGuidBoilerplate()
    {
        const string source = @"
using System;
using EricksonLopez.DomainPrimitives;

namespace TestNamespace;

[StrongId<Guid>]
public readonly partial record struct OrderId(Guid Value);
";

        var runResult = RunGeneratorDriver<StrongIdGenerator>(source);

        var tree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("OrderId.g.cs", StringComparison.Ordinal));
        tree.Should().NotBeNull();
        var output = Normalize(tree!.ToString());

        const string expectedOutput = @"// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    partial readonly record struct OrderId : global::EricksonLopez.DomainPrimitives.IStrongId<OrderId, global::System.Guid>
    {
        /// <inheritdoc/>
        public static string PrimitiveName => ""OrderId"";

        /// <inheritdoc/>
        public bool IsDefault => global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(Value, default!);

        /// <summary>
        /// Creates a new instance of <see cref=""OrderId""/>.
        /// </summary>
        public static OrderId Create(global::System.Guid value) => new(value);

        /// <inheritdoc/>
        public static bool TryCreate(global::System.Guid value, out OrderId result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
        {
            result = new(value);
            validationError = default;
            return true;
        }

        /// <summary>
        /// Creates a new <see cref=""OrderId""/> initialized with a sequential UUIDv7 or new Guid.
        /// </summary>
        public static OrderId New() => new(global::System.Guid.NewGuid());

        /// <summary>
        /// Creates a new, unique identifier.
        /// </summary>
        public static OrderId Create() => new(global::System.Guid.NewGuid());

        /// <summary>
        /// Gets an empty <see cref=""OrderId""/> instance.
        /// </summary>
        public static OrderId Empty => new(global::System.Guid.Empty);

        /// <summary>
        /// Gets a value indicating whether this identifier is empty.
        /// </summary>
        public bool IsEmpty => Value == global::System.Guid.Empty;

        /// <inheritdoc/>
        public override string ToString() => Value.ToString();

        public static implicit operator global::System.Guid(OrderId id) => id.Value;
        public static explicit operator OrderId(global::System.Guid value) => new(value);
    }
}";

        output.Should().Be(Normalize(expectedOutput));
    }

    [Fact]
    public void Generator_WithTypeOfAttribute_AndIntUnderlyingType_GeneratesUnsupportedParameterlessCreate()
    {
        const string source = @"
using System;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.SharedKernel;

namespace TestNamespace;

[StrongId(typeof(int))]
public readonly partial record struct DepartmentId(int Value);
";

        var runResult = RunGeneratorDriver<StrongIdGenerator>(source);

        var tree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("DepartmentId.g.cs", StringComparison.Ordinal));
        tree.Should().NotBeNull();
        var output = Normalize(tree!.ToString());

        const string expectedOutput = @"// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    partial readonly record struct DepartmentId : global::EricksonLopez.DomainPrimitives.IStrongId<DepartmentId, int>
    {
        /// <inheritdoc/>
        public static string PrimitiveName => ""DepartmentId"";

        /// <inheritdoc/>
        public bool IsDefault => global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(Value, default!);

        /// <summary>
        /// Creates a new instance of <see cref=""DepartmentId""/>.
        /// </summary>
        public static DepartmentId Create(int value) => new(value);

        /// <inheritdoc/>
        public static bool TryCreate(int value, out DepartmentId result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
        {
            result = new(value);
            validationError = default;
            return true;
        }

        /// <summary>
        /// Parameterless creation is not supported for non-Guid types.
        /// </summary>
        public static DepartmentId Create() => throw new global::System.NotSupportedException(""Parameterless Create() is only supported for Guid-backed strong IDs."");

        /// <summary>
        /// Gets an empty <see cref=""DepartmentId""/> instance.
        /// </summary>
        public static DepartmentId Empty => new(default!);

        /// <inheritdoc/>
        public override string ToString() => Value.ToString();

        public static implicit operator int(DepartmentId id) => id.Value;
        public static explicit operator DepartmentId(int value) => new(value);
    }
}";

        output.Should().Be(Normalize(expectedOutput));
    }

    [Fact]
    public void Generator_WithoutPrimaryConstructorValueProperty_GeneratesValueProperty()
    {
        const string source = @"
using System;
using EricksonLopez.DomainPrimitives;

namespace TestNamespace;

[StrongId<Guid>]
public partial record struct EmptyId;
";

        var runResult = RunGeneratorDriver<StrongIdGenerator>(source);

        var tree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("EmptyId.g.cs", StringComparison.Ordinal));
        tree.Should().NotBeNull();
        var output = Normalize(tree!.ToString());

        const string expectedEmptyIdOutput = @"// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    partial readonly record struct EmptyId : global::EricksonLopez.DomainPrimitives.IStrongId<EmptyId, global::System.Guid>
    {
        public global::System.Guid Value { get; init; }

        /// <inheritdoc/>
        public static string PrimitiveName => ""EmptyId"";

        /// <inheritdoc/>
        public bool IsDefault => global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(Value, default!);

        /// <summary>
        /// Creates a new instance of <see cref=""EmptyId""/>.
        /// </summary>
        public static EmptyId Create(global::System.Guid value) => new(value);

        /// <inheritdoc/>
        public static bool TryCreate(global::System.Guid value, out EmptyId result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
        {
            result = new(value);
            validationError = default;
            return true;
        }

        /// <summary>
        /// Creates a new <see cref=""EmptyId""/> initialized with a sequential UUIDv7 or new Guid.
        /// </summary>
        public static EmptyId New() => new(global::System.Guid.NewGuid());

        /// <summary>
        /// Creates a new, unique identifier.
        /// </summary>
        public static EmptyId Create() => new(global::System.Guid.NewGuid());

        /// <summary>
        /// Gets an empty <see cref=""EmptyId""/> instance.
        /// </summary>
        public static EmptyId Empty => new(global::System.Guid.Empty);

        /// <summary>
        /// Gets a value indicating whether this identifier is empty.
        /// </summary>
        public bool IsEmpty => Value == global::System.Guid.Empty;

        /// <inheritdoc/>
        public override string ToString() => Value.ToString();

        public static implicit operator global::System.Guid(EmptyId id) => id.Value;
        public static explicit operator EmptyId(global::System.Guid value) => new(value);
    }
}";

        output.Should().Be(Normalize(expectedEmptyIdOutput));
    }

    [Fact]
    public void Generator_WithMultipleAttributesAndInterfaces_FirstStrongIdWins()
    {
        const string source = @"
using System;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.SharedKernel;

namespace TestNamespace;

[StrongId<Guid>]
[StrongId<int>]
public readonly partial record struct MultiGenericAttrId(Guid Value);

[StrongId(typeof(Guid))]
[StrongId(typeof(int))]
public readonly partial record struct MultiTypeofAttrId(Guid Value);

public readonly partial record struct MultiIfaceId(Guid Value) : IStrongId<MultiIfaceId, Guid>, IDisposable
{
    public void Dispose() { }
}
";

        var runResult = RunGeneratorDriver<StrongIdGenerator>(source);

        var tree1 = runResult.GeneratedTrees.First(t => t.FilePath.EndsWith("MultiGenericAttrId.g.cs", StringComparison.Ordinal)).ToString();
        tree1.Should().Contain("IStrongId<MultiGenericAttrId, global::System.Guid>");

        var tree2 = runResult.GeneratedTrees.First(t => t.FilePath.EndsWith("MultiTypeofAttrId.g.cs", StringComparison.Ordinal)).ToString();
        tree2.Should().Contain("IStrongId<MultiTypeofAttrId, global::System.Guid>");

        var tree3 = runResult.GeneratedTrees.First(t => t.FilePath.EndsWith("MultiIfaceId.g.cs", StringComparison.Ordinal)).ToString();
        tree3.Should().Contain("IStrongId<MultiIfaceId, global::System.Guid>");
    }

    [Fact]
    public void Generator_WithCustomStrongIdWithoutAttributeSuffix_GeneratesCode()
    {
        const string source = @"
using System;
using EricksonLopez.DomainPrimitives;

namespace CustomAttrs
{
    [AttributeUsage(AttributeTargets.Struct)]
    public class StrongId<T> : Attribute { }

    [AttributeUsage(AttributeTargets.Struct)]
    public class StrongId : Attribute
    {
        public Type ValueType { get; }
        public StrongId(Type type) => ValueType = type;
    }
}

namespace TestNamespace
{
    using CustomAttrs;

    [StrongId<Guid>]
    public readonly partial record struct CustomSuffixGenericId(Guid Value);

    [StrongId(typeof(int))]
    public readonly partial record struct CustomSuffixNonGenericId(int Value);
}
";

        var runResult = RunGeneratorDriver<StrongIdGenerator>(source);

        var tree1 = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("CustomSuffixGenericId.g.cs", StringComparison.Ordinal));
        tree1.Should().NotBeNull();

        var tree2 = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("CustomSuffixNonGenericId.g.cs", StringComparison.Ordinal));
        tree2.Should().NotBeNull();
    }

    [Fact]
    public void Generator_WithTwoArgStrongIdAttributeOrMismatchedInterface_DoesNotGenerateCode()
    {
        const string source = @"
using System;
using EricksonLopez.DomainPrimitives;

namespace EricksonLopez.SharedKernel
{
    [AttributeUsage(AttributeTargets.Struct)]
    public class StrongId<T1, T2> : Attribute { }
}

namespace TestNamespace
{
    using EricksonLopez.SharedKernel;

    public readonly record struct OtherId(Guid Value);

    [StrongId<int, string>]
    public readonly partial record struct TwoArgAttrId(int Value);

    public readonly partial record struct MismatchedIfaceId(Guid Value) : IStrongId<OtherId, Guid>;
}
";

        var runResult = RunGeneratorDriver<StrongIdGenerator>(source);

        runResult.GeneratedTrees.Any(t => t.FilePath.EndsWith("TwoArgAttrId.g.cs", StringComparison.Ordinal)).Should().BeFalse();
        runResult.GeneratedTrees.Any(t => t.FilePath.EndsWith("MismatchedIfaceId.g.cs", StringComparison.Ordinal)).Should().BeFalse();
    }

    [Fact]
    public void Generator_WithClass_Struct_ReadonlyStruct_RecordClass_GeneratesAppropriateKeywordsAndEquality()
    {
        const string source = @"
using System;
using EricksonLopez.DomainPrimitives;

namespace TestNamespace;

[StrongId<Guid>]
public partial class ClassId
{
    public Guid Value { get; init; }
}

[StrongId<int>]
public partial struct StructId
{
    public int Value { get; init; }
}

[StrongId<int>]
public readonly partial struct ReadonlyStructId
{
    public int Value { get; init; }
}

[StrongId<string>]
public partial record class RecordClassId(string Value);
";

        var runResult = RunGeneratorDriver<StrongIdGenerator>(source);

        var classTree = Normalize(runResult.GeneratedTrees.First(t => t.FilePath.EndsWith("ClassId.g.cs", StringComparison.Ordinal)).ToString());
        const string expectedClassOutput = @"// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    partial class ClassId : global::EricksonLopez.DomainPrimitives.IStrongId<ClassId, global::System.Guid>
    {
        /// <inheritdoc/>
        public static string PrimitiveName => ""ClassId"";

        /// <inheritdoc/>
        public bool IsDefault => global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(Value, default!);

        /// <summary>
        /// Creates a new instance of <see cref=""ClassId""/>.
        /// </summary>
        public static ClassId Create(global::System.Guid value) => new(value);

        /// <inheritdoc/>
        public static bool TryCreate(global::System.Guid value, out ClassId result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
        {
            result = new(value);
            validationError = default;
            return true;
        }

        /// <summary>
        /// Creates a new <see cref=""ClassId""/> initialized with a sequential UUIDv7 or new Guid.
        /// </summary>
        public static ClassId New() => new(global::System.Guid.NewGuid());

        /// <summary>
        /// Creates a new, unique identifier.
        /// </summary>
        public static ClassId Create() => new(global::System.Guid.NewGuid());

        /// <summary>
        /// Gets an empty <see cref=""ClassId""/> instance.
        /// </summary>
        public static ClassId Empty => new(global::System.Guid.Empty);

        /// <summary>
        /// Gets a value indicating whether this identifier is empty.
        /// </summary>
        public bool IsEmpty => Value == global::System.Guid.Empty;

        /// <inheritdoc/>
        public override string ToString() => Value.ToString();

        public static implicit operator global::System.Guid(ClassId id) => id.Value;
        public static explicit operator ClassId(global::System.Guid value) => new(value);

        public bool Equals(ClassId other) => Value.Equals(other.Value);
        public override bool Equals(object? obj) => obj is ClassId other && Equals(other);
        public override int GetHashCode() => Value.GetHashCode();
        public static bool operator ==(ClassId left, ClassId right) => left.Equals(right);
        public static bool operator !=(ClassId left, ClassId right) => !left.Equals(right);
    }
}";
        classTree.Should().Be(Normalize(expectedClassOutput));

        var structTree = runResult.GeneratedTrees.First(t => t.FilePath.EndsWith("StructId.g.cs", StringComparison.Ordinal)).ToString();
        structTree.Should().Contain("partial struct StructId");
        structTree.Should().Contain("public bool Equals(StructId other) => Value.Equals(other.Value);");

        var readonlyStructTree = runResult.GeneratedTrees.First(t => t.FilePath.EndsWith("ReadonlyStructId.g.cs", StringComparison.Ordinal)).ToString();
        readonlyStructTree.Should().Contain("partial readonly struct ReadonlyStructId");

        var recordClassTree = runResult.GeneratedTrees.First(t => t.FilePath.EndsWith("RecordClassId.g.cs", StringComparison.Ordinal)).ToString();
        recordClassTree.Should().Contain("partial record class RecordClassId");
        recordClassTree.Should().NotContain("public static bool operator ==");
    }

    [Fact]
    public void Generator_InGlobalNamespace_GeneratesCodeWithoutNamespaceWrapper()
    {
        const string source = @"
using System;
using EricksonLopez.DomainPrimitives;

[StrongId<Guid>]
public readonly partial record struct GlobalOrderId(Guid Value);
";

        var runResult = RunGeneratorDriver<StrongIdGenerator>(source);

        var tree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("GlobalOrderId.g.cs", StringComparison.Ordinal));
        tree.Should().NotBeNull();
        var output = Normalize(tree!.ToString());

        const string expectedGlobalOutput = @"// <auto-generated/>
#nullable enable

partial readonly record struct GlobalOrderId : global::EricksonLopez.DomainPrimitives.IStrongId<GlobalOrderId, global::System.Guid>
{
    /// <inheritdoc/>
    public static string PrimitiveName => ""GlobalOrderId"";

    /// <inheritdoc/>
    public bool IsDefault => global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(Value, default!);

    /// <summary>
    /// Creates a new instance of <see cref=""GlobalOrderId""/>.
    /// </summary>
    public static GlobalOrderId Create(global::System.Guid value) => new(value);

    /// <inheritdoc/>
    public static bool TryCreate(global::System.Guid value, out GlobalOrderId result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
    {
        result = new(value);
        validationError = default;
        return true;
    }

    /// <summary>
    /// Creates a new <see cref=""GlobalOrderId""/> initialized with a sequential UUIDv7 or new Guid.
    /// </summary>
    public static GlobalOrderId New() => new(global::System.Guid.NewGuid());

    /// <summary>
    /// Creates a new, unique identifier.
    /// </summary>
    public static GlobalOrderId Create() => new(global::System.Guid.NewGuid());

    /// <summary>
    /// Gets an empty <see cref=""GlobalOrderId""/> instance.
    /// </summary>
    public static GlobalOrderId Empty => new(global::System.Guid.Empty);

    /// <summary>
    /// Gets a value indicating whether this identifier is empty.
    /// </summary>
    public bool IsEmpty => Value == global::System.Guid.Empty;

    /// <inheritdoc/>
    public override string ToString() => Value.ToString();

    public static implicit operator global::System.Guid(GlobalOrderId id) => id.Value;
    public static explicit operator GlobalOrderId(global::System.Guid value) => new(value);
}";

        output.Should().Be(Normalize(expectedGlobalOutput));
    }

    [Fact]
    public void Generator_WithIStrongIdInterfaceImplementation_DiscoversUnderlyingType()
    {
        const string source = @"
using System;
using EricksonLopez.DomainPrimitives;

namespace TestNamespace;

public readonly partial record struct InterfaceId(Guid Value) : IStrongId<InterfaceId, Guid>;
";

        var runResult = RunGeneratorDriver<StrongIdGenerator>(source);

        var tree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("InterfaceId.g.cs", StringComparison.Ordinal));
        tree.Should().NotBeNull();
        var output = Normalize(tree!.ToString());

        output.Should().Contain("public static InterfaceId Create(global::System.Guid value) => new(value);");
        output.Should().Contain("public static InterfaceId New() => new(global::System.Guid.NewGuid());");
    }

    [Fact]
    public void Generator_WithNonMatchingInterface_DoesNotGenerateSource()
    {
        const string source = @"
using System;

namespace TestNamespace;

public interface IOther<T1, T2>;
public interface IStrongId<T>;
public interface IStrongId<T1, T2, T3>;

public readonly partial record struct OtherInterfaceId(Guid Value) : IOther<OtherInterfaceId, Guid>;
public readonly partial record struct WrongTypeArgId(Guid Value) : EricksonLopez.DomainPrimitives.IStrongId<WrongTypeArgId, Guid>
{
    // Deliberately implementing interface with other type
}
";

        var runResult = RunGeneratorDriver<StrongIdGenerator>(source);

        // WrongTypeArgId implements IStrongId<WrongTypeArgId, Guid> so it generates, but OtherInterfaceId should not generate separate tree
        runResult.GeneratedTrees.Any(t => t.FilePath.EndsWith("OtherInterfaceId.g.cs", StringComparison.Ordinal)).Should().BeFalse();
    }

    [Fact]
    public void Generator_WithNonPartialOrNonStrongId_DoesNotGenerateSource()
    {
        const string source = @"
using System;

namespace TestNamespace;

public class NormalClass { }
public struct NormalStruct { }
";

        var runResult = RunGeneratorDriver<StrongIdGenerator>(source);

        runResult.GeneratedTrees.Length.Should().Be(1);
        runResult.GeneratedTrees[0].FilePath.EndsWith("StrongIdAttribute.g.cs", StringComparison.Ordinal).Should().BeTrue();
    }

    [Fact]
    public void GetStrongIdTarget_WhenDeclaredSymbolIsNull_ReturnsNull()
    {
        var method = typeof(StrongIdGenerator).GetMethod("GetStrongIdTarget", BindingFlags.NonPublic | BindingFlags.Static);
        method.Should().NotBeNull();

        var tree = CSharpSyntaxTree.ParseText("public class Sample { }");
        var node = tree.GetRoot().DescendantNodes().OfType<TypeDeclarationSyntax>().First();

        var semanticModel = Substitute.For<SemanticModel>();
        semanticModel.GetDeclaredSymbol(Arg.Any<SyntaxNode>(), Arg.Any<System.Threading.CancellationToken>()).Returns((ISymbol?)null);

        var contextType = typeof(GeneratorSyntaxContext);
        var ctor = contextType.GetConstructors(BindingFlags.NonPublic | BindingFlags.Instance).First();
        var context = ctor.Invoke(new object[] { node, new Lazy<SemanticModel>(() => semanticModel), null! });

        var result = method!.Invoke(null, new object[] { context, System.Threading.CancellationToken.None });
        result.Should().BeNull();
    }

    [Fact]
    public void GetStrongIdTarget_WhenInterfaceNodePassed_TriggersFallbackTypeKind()
    {
        var method = typeof(StrongIdGenerator).GetMethod("GetStrongIdTarget", BindingFlags.NonPublic | BindingFlags.Static);
        method.Should().NotBeNull();

        const string source = @"
using System;
using EricksonLopez.DomainPrimitives;

namespace TestNamespace
{
    [StrongId<Guid>]
    public partial interface ICustomId : IStrongId<ICustomId, Guid>;
}
";
        var tree = CSharpSyntaxTree.ParseText(source);
        var references = new MetadataReference[]
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Attribute).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(IStrongId<,>).Assembly.Location),
        };
        var compilation = CSharpCompilation.Create("TestComp", new[] { tree }, references, new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        var semanticModel = compilation.GetSemanticModel(tree);

        var node = tree.GetRoot().DescendantNodes().OfType<TypeDeclarationSyntax>().First();

        var contextType = typeof(GeneratorSyntaxContext);
        var ctor = contextType.GetConstructors(BindingFlags.NonPublic | BindingFlags.Instance).First();
        var context = ctor.Invoke(new object[] { node, new Lazy<SemanticModel>(() => semanticModel), null! });

        var result = method!.Invoke(null, new object[] { context, System.Threading.CancellationToken.None });
        result.Should().NotBeNull();
    }

    [Fact]
    public void StrongIdTarget_EqualityAndHashCode_WorkCorrectly()
    {
        var targetType = typeof(StrongIdGenerator).Assembly
            .GetType("EricksonLopez.SharedKernel.SourceGenerators.StrongIdGenerator+StrongIdTarget");

        targetType.Should().NotBeNull();

        var target1 = Activator.CreateInstance(targetType!, "App", "OrderId", "readonly record struct", "global::System.Guid", "Guid", true, true);
        var target2 = Activator.CreateInstance(targetType!, "App", "OrderId", "readonly record struct", "global::System.Guid", "Guid", true, true);
        var target3 = Activator.CreateInstance(targetType!, "App", "CustomerId", "readonly record struct", "global::System.Guid", "Guid", true, true);
        var target4 = Activator.CreateInstance(targetType!, "OtherApp", "OrderId", "readonly record struct", "global::System.Guid", "Guid", true, true);
        var target5 = Activator.CreateInstance(targetType!, "App", "OrderId", "class", "global::System.Guid", "Guid", true, true);
        var target6 = Activator.CreateInstance(targetType!, "App", "OrderId", "readonly record struct", "int", "int", true, true);
        var target7 = Activator.CreateInstance(targetType!, "App", "OrderId", "readonly record struct", "global::System.Guid", "Guid", false, true);
        var target8 = Activator.CreateInstance(targetType!, "App", "OrderId", "readonly record struct", "global::System.Guid", "Guid", true, false);

        target1.Should().Be(target2);
        target1.Should().NotBe(target3);
        target1.Should().NotBe(target4);
        target1.Should().NotBe(target5);
        target1.Should().NotBe(target6);
        target1.Should().NotBe(target7);
        target1.Should().NotBe(target8);
        target1.Should().NotBe(null);
        target1.Should().NotBe(new object());
        target1!.GetHashCode().Should().Be(target2!.GetHashCode());
    }

    [Fact]
    public void Generator_WithStrongIdWithoutAttributeSuffix_GeneratesStrongId()
    {
        const string source = @"
using System;

namespace CustomAttrs
{
    [AttributeUsage(AttributeTargets.Struct)]
    public class StrongId<T> : Attribute { }

    [AttributeUsage(AttributeTargets.Struct)]
    public class StrongId : Attribute
    {
        public Type ValueType { get; }
        public StrongId(Type type) => ValueType = type;
    }

    [AttributeUsage(AttributeTargets.Struct)]
    public class NonMatchingAttribute : Attribute { }
}

namespace SampleApp
{
    using CustomAttrs;

    [NonMatching]
    [StrongId<Guid>]
    public readonly partial record struct CustomSuffixGenericId(Guid Value);

    [NonMatching]
    [StrongId(typeof(int))]
    public readonly partial record struct CustomSuffixNonGenericId(int Value);

    [NonMatching]
    public readonly partial record struct NonStrongIdStruct(int Value);
}
";

        var runResult = RunGeneratorDriver<StrongIdGenerator>(source);

        var tree1 = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("CustomSuffixGenericId.g.cs", StringComparison.Ordinal));
        tree1.Should().NotBeNull();

        var tree2 = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("CustomSuffixNonGenericId.g.cs", StringComparison.Ordinal));
        tree2.Should().NotBeNull();

        var tree3 = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.EndsWith("NonStrongIdStruct.g.cs", StringComparison.Ordinal));
        tree3.Should().BeNull();
    }

    private static GeneratorDriverRunResult RunGeneratorDriver<TGenerator>(string source)
        where TGenerator : IIncrementalGenerator, new()
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source);
        var references = new MetadataReference[]
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Attribute).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(IStrongId<,>).Assembly.Location),
        };

        var compilation = CSharpCompilation.Create(
            "TestCompilation",
            new[] { syntaxTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new TGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out _, out var diagnostics);
        diagnostics.Should().NotContain(d => d.Severity == DiagnosticSeverity.Error);

        return driver.GetRunResult();
    }
}
