// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EricksonLopez.SharedKernel.SourceGenerators;

/// <summary>
/// Generates compile-time Dapper type handler registrations for strongly-typed identifiers to ensure Native AOT and trimming compatibility.
/// </summary>
[Generator]
public sealed class DapperRegistrationGenerator : IIncrementalGenerator
{
    private const string AttributeSource = @"// <auto-generated/>
#nullable enable
namespace EricksonLopez.SharedKernel.Dapper
{
    /// <summary>
    /// Instructs the source generator to generate compile-time Native AOT Dapper type handler registrations for all StrongIds in this compilation.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly | global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class GenerateDapperStrongIdRegistrationsAttribute : global::System.Attribute
    {
    }
}
";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Post-initialization marker attribute
        context.RegisterPostInitializationOutput(static postContext =>
        {
            postContext.AddSource("GenerateDapperStrongIdRegistrationsAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
        });

        // 2. Discover all IStrongId implementations in compilation
        var strongIdTypes = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is TypeDeclarationSyntax,
            transform: static (genContext, ct) => GetStrongIdTypeInfo(genContext, ct))
            .Where(static target => target is not null)
            .Collect();

        // 3. Generate the AOT bulk registration class
        context.RegisterSourceOutput(strongIdTypes, static (sourceContext, types) =>
        {
            if (types.IsDefaultOrEmpty)
                return;

            var distinctTypes = types
                .Select(t => t!.Value)
                .Distinct()
                .OrderBy(t => t.FullTypeName)
                .ToList();

            GenerateDapperRegistrationSource(sourceContext, distinctTypes);
        });
    }

    private static DapperStrongIdItem? GetStrongIdTypeInfo(GeneratorSyntaxContext context, System.Threading.CancellationToken ct)
    {
        var typeDeclaration = (TypeDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(typeDeclaration, ct) is not INamedTypeSymbol typeSymbol)
            return null;

        if (typeSymbol.IsAbstract)
            return null;

        ITypeSymbol? underlyingType = null;

        // Check attributes: [StrongId(typeof(T))] or [StrongId<T>]
        foreach (var attribute in typeSymbol.GetAttributes())
        {
            var attrClass = attribute.AttributeClass;
            // Stryker disable once Statement : Defensive null check for Roslyn attribute class symbol
            if (attrClass is null) continue;

            if (attrClass.Name is "StrongIdAttribute" or "StrongId")
            {
                if (attrClass.IsGenericType && attrClass.TypeArguments.Length == 1)
                {
                    underlyingType = attrClass.TypeArguments[0];
                    break;
                }

                if (attribute.ConstructorArguments.Length == 1 &&
                    attribute.ConstructorArguments[0].Value is ITypeSymbol constructorType)
                {
                    underlyingType = constructorType;
                    break;
                }
            }
        }

        // Check interface implementation: IStrongId<TSelf, TValue>
        if (underlyingType is null)
        {
            foreach (var iface in typeSymbol.AllInterfaces)
            {
                // Stryker disable once Logical, Boolean, Unary : Compiler redundancy between IsGenericType and TypeArguments.Length
                if (iface.IsGenericType &&
                    iface.TypeArguments.Length == 2 &&
                    iface.Name == "IStrongId")
                {
                    underlyingType = iface.TypeArguments[1];
                    // Stryker disable once Statement : Loop-exit optimization
                    break;
                }
            }
        }

        if (underlyingType is null)
            return null;

        return new DapperStrongIdItem(
            FullTypeName: typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            UnderlyingTypeDisplay: underlyingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
    }

    private static void GenerateDapperRegistrationSource(SourceProductionContext context, List<DapperStrongIdItem> items)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace EricksonLopez.SharedKernel.Dapper");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Compile-time generated Native AOT &amp; Trimming safe Dapper StrongId registrations.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class GeneratedDapperStrongIdRegistryExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Registers all discovered Strongly-Typed IDs with Dapper's SqlMapper without runtime reflection.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void RegisterAllGeneratedStrongIds()");
        sb.AppendLine("        {");

        foreach (var item in items)
        {
            sb.AppendLine($"            global::EricksonLopez.SharedKernel.Dapper.DapperStrongIdRegistry.Register<{item.FullTypeName}, {item.UnderlyingTypeDisplay}>();");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedDapperStrongIdRegistryExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private readonly struct DapperStrongIdItem : IEquatable<DapperStrongIdItem>
    {
        public string FullTypeName { get; }
        public string UnderlyingTypeDisplay { get; }

        public DapperStrongIdItem(string FullTypeName, string UnderlyingTypeDisplay)
        {
            this.FullTypeName = FullTypeName;
            this.UnderlyingTypeDisplay = UnderlyingTypeDisplay;
        }

        public bool Equals(DapperStrongIdItem other) =>
            FullTypeName == other.FullTypeName &&
            UnderlyingTypeDisplay == other.UnderlyingTypeDisplay;

        public override bool Equals(object? obj) => obj is DapperStrongIdItem other && Equals(other);
        public override int GetHashCode() => (FullTypeName, UnderlyingTypeDisplay).GetHashCode();
    }
}
