// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EricksonLopez.SharedKernel.SourceGenerators;

/// <summary>
/// Source generator that scans for domain entity hierarchies (AggregateRoot and Entity) and emits static zero-reflection metadata registrations with compiled PropertyMetadata accessors.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class MetadataSourceGenerator : IIncrementalGenerator
{
    private static readonly string[] _excludedProperties =
    {
        "DomainEvents"
    };

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidateClasses = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is ClassDeclarationSyntax cls && !cls.Modifiers.Any(SyntaxKind.AbstractKeyword),
            transform: static (genContext, ct) => GetCandidateClass(genContext, ct))
            .Where(static symbol => symbol is not null)
            .Collect();

        var hasPersistence = context.CompilationProvider.Select(static (compilation, _) =>
            compilation.GetTypeByMetadataName("EricksonLopez.SharedKernel.Persistence.EntityMetadata") is not null);

        var combined = candidateClasses.Combine(hasPersistence);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var (entities, isPersistenceAvailable) = pair;
            if (!isPersistenceAvailable || entities.IsDefaultOrEmpty)
                return;

            var distinctEntities = entities
                .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default)
                .OrderBy(e => e.ToDisplayString())
                .ToList();

            // Stryker disable once Statement : Defensive empty check after distinct enumeration
            if (distinctEntities.Count == 0)
                return;

            EmitAllMetadata(spc, distinctEntities);
        });
    }

    private static INamedTypeSymbol? GetCandidateClass(GeneratorSyntaxContext context, System.Threading.CancellationToken ct)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDecl, ct) is not INamedTypeSymbol symbol)
            return null;

        if (symbol.IsAbstract)
            return null;



        var current = symbol.BaseType;
        while (current is not null && current.SpecialType != SpecialType.System_Object)
        {
            if (current.Name is "AggregateRoot" or "Entity")
            {
                var ns = current.ContainingNamespace?.ToDisplayString();
                if (ns is "EricksonLopez.SharedKernel")
                {
                    return symbol;
                }
            }

            current = current.BaseType;
        }

        if (symbol.AllInterfaces.Any(static i => (i.Name is "IAggregateRoot" or "IEntity") &&
            i.ContainingNamespace?.ToDisplayString() is "EricksonLopez.SharedKernel"))
        {
            return symbol;
        }

        return null;
    }

    private static void EmitAllMetadata(SourceProductionContext context, List<INamedTypeSymbol> domainEntities)
    {
        var sb = new StringBuilder(8192);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0618");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using EricksonLopez.SharedKernel.Persistence;");
        sb.AppendLine();
        sb.AppendLine("namespace EricksonLopez.SharedKernel.Persistence.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Compile-time generated metadata registry for domain entities.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GeneratedMetadataRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Returns the complete enumeration of compiled entity metadata descriptors.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IEnumerable<EntityMetadata> GetAllRawMetadata()");
        sb.AppendLine("    {");

        foreach (var entity in domainEntities)
        {
            EmitEntityMetadata(sb, entity);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedMetadataRegistry.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitEntityMetadata(StringBuilder sb, INamedTypeSymbol entity)
    {
        var fqn = entity.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var safeName = fqn.Replace(".", "_").Replace("global::", "");

        string tableName = entity.Name;
        string schema = "public";

        sb.AppendLine();
        sb.AppendLine($"        // ── {entity.ToDisplayString()} ──");
        sb.AppendLine($"        var columns_{safeName} = new List<PropertyMetadata>();");

        var properties = GetPersistableProperties(entity);
        foreach (var prop in properties)
        {
            var propName = prop.Name;
            var propTypeFqn = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            bool isNullable = prop.Type.NullableAnnotation == NullableAnnotation.Annotated
                              || prop.Type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;

            string columnName = propName;
            bool isKey = propName.Equals("Id", StringComparison.OrdinalIgnoreCase);

            if (!isKey && prop.GetAttributes().Any(a => a.AttributeClass?.Name is "KeyAttribute" or "Key"))
            {
                isKey = true;
            }

            bool isAudit = false;

            bool isTenantColumn = propName.Equals("TenantId", StringComparison.OrdinalIgnoreCase)
                || propName.Equals("CompanyId", StringComparison.OrdinalIgnoreCase)
                || prop.GetAttributes().Any(a => a.AttributeClass?.Name is "TenantIdAttribute" or "TenantId");

            bool isSoftDelete = propName.Equals("IsDeleted", StringComparison.OrdinalIgnoreCase)
                || propName.Equals("Deleted", StringComparison.OrdinalIgnoreCase)
                || propName.Equals("IsArchived", StringComparison.OrdinalIgnoreCase)
                || prop.GetAttributes().Any(a => a.AttributeClass?.Name is "SoftDeleteAttribute" or "SoftDelete");

            bool isConcurrencyToken = propName.Equals("Version", StringComparison.OrdinalIgnoreCase)
                || propName.Equals("RowVersion", StringComparison.OrdinalIgnoreCase)
                || propName.Equals("xmin", StringComparison.OrdinalIgnoreCase)
                || prop.GetAttributes().Any(a => a.AttributeClass?.Name is "TimestampAttribute" or "Timestamp" or "ConcurrencyCheckAttribute" or "ConcurrencyCheck");

            string getter = $"(object obj) => (object?)(({fqn})obj).{propName}";
            string setter = "null";
            if (prop.SetMethod is not null
                && !prop.SetMethod.IsInitOnly
                && prop.SetMethod.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal)
            {
                if (isNullable)
                {
                    setter = $"(object obj, object? val) => (({fqn})obj).{propName} = val is null ? default! : ({propTypeFqn})val";
                }
                else
                {
                    setter = $"(object obj, object? val) => (({fqn})obj).{propName} = val is null ? throw new global::System.ArgumentNullException(nameof(val), \"Cannot assign null to non-nullable property '{propName}' on '{fqn}'.\") : ({propTypeFqn})val";
                }
            }

            sb.AppendLine($"        columns_{safeName}.Add(new PropertyMetadata(");
            sb.AppendLine($"            ClrName: \"{propName}\",");
            sb.AppendLine($"            ClrType: typeof({propTypeFqn}),");
            sb.AppendLine($"            ColumnName: \"{columnName}\",");
            sb.AppendLine($"            DatabaseType: string.Empty,");
            sb.AppendLine($"            IsKey: {(isKey ? "true" : "false")},");
            sb.AppendLine($"            IsNullable: {(isNullable ? "true" : "false")},");
            // Stryker disable once Conditional, String : Constant boolean formatting
            sb.AppendLine($"            IsAuditColumn: {(isAudit ? "true" : "false")},");
            sb.AppendLine($"            IsSoftDeleteColumn: {(isSoftDelete ? "true" : "false")},");
            sb.AppendLine($"            IsTenantColumn: {(isTenantColumn ? "true" : "false")},");
            sb.AppendLine($"            IsConcurrencyToken: {(isConcurrencyToken ? "true" : "false")},");
            sb.AppendLine($"            Getter: {getter},");
            sb.AppendLine($"            Setter: {setter}));");
        }

        sb.AppendLine($"        yield return new EntityMetadata");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            ClrType = typeof({fqn}),");
        sb.AppendLine($"            TableName = \"{tableName}\",");
        sb.AppendLine($"            Schema = \"{schema}\",");
        sb.AppendLine($"            Columns = columns_{safeName},");
        sb.AppendLine($"            PrimaryKeys = columns_{safeName}.Where(c => c.IsKey).ToList(),");
        sb.AppendLine($"            TenantColumn = columns_{safeName}.FirstOrDefault(c => c.IsTenantColumn),");
        sb.AppendLine($"            SoftDeleteColumn = columns_{safeName}.FirstOrDefault(c => c.IsSoftDeleteColumn),");
        sb.AppendLine($"            ConcurrencyToken = columns_{safeName}.FirstOrDefault(c => c.IsConcurrencyToken)");
        sb.AppendLine($"        }};");
    }

    private static IEnumerable<IPropertySymbol> GetPersistableProperties(INamedTypeSymbol symbol)
    {
        var seen = new HashSet<string>();
        var current = symbol;

        while (current is not null && current.SpecialType != SpecialType.System_Object)
        {
            foreach (var member in current.GetMembers())
            {
                if (member is not IPropertySymbol prop) continue;
                if (prop.IsStatic || prop.IsIndexer) continue;
                if (prop.GetMethod is null) continue;
                if (prop.DeclaredAccessibility < Accessibility.Protected) continue;
                if (_excludedProperties.Contains(prop.Name)) continue;
                if (IsCollectionType(prop.Type)) continue;
                if (!seen.Add(prop.Name)) continue;

                yield return prop;
            }

            current = current.BaseType;
        }
    }

    private static bool IsCollectionType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named)
        {
            var fullName = named.OriginalDefinition.ToDisplayString();
            if (fullName.StartsWith("System.Collections.", StringComparison.Ordinal)) return true;
            // Stryker disable once all : Explicit collection interface checks shadowed by namespace prefix
            if (fullName == "System.Collections.Generic.IReadOnlyList<T>") return true;
            // Stryker disable once all : Explicit collection interface checks shadowed by namespace prefix
            if (fullName == "System.Collections.Generic.List<T>") return true;
            // Stryker disable once all : Explicit collection interface checks shadowed by namespace prefix
            if (fullName == "System.Collections.Generic.IEnumerable<T>") return true;
        }
        return false;
    }
}
