// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EricksonLopez.SharedKernel.SourceGenerators;

/// <summary>
/// Generates strongly-typed identifier boilerplate implementations and domain primitive interfaces at compile time.
/// </summary>
[Generator]
public sealed class StrongIdGenerator : IIncrementalGenerator
{
    private const string AttributeSource = @"// <auto-generated/>
#nullable enable
namespace EricksonLopez.SharedKernel
{
    /// <summary>
    /// Marks a type as a strongly-typed identifier to generate factory methods, operators, and formatting.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class StrongIdAttribute : global::System.Attribute
    {
        public global::System.Type ValueType { get; }

        public StrongIdAttribute(global::System.Type valueType)
        {
            ValueType = valueType;
        }
    }

    /// <summary>
    /// Generic attribute to mark a type as a strongly-typed identifier with underlying type <typeparamref name=""TValue""/>.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class StrongIdAttribute<TValue> : global::System.Attribute
        where TValue : notnull, global::System.IEquatable<TValue>
    {
    }
}
";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Register marker attributes
        context.RegisterPostInitializationOutput(static postContext =>
        {
            postContext.AddSource("StrongIdAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
        });

        // 2. Syntax provider for type declarations decorated with StrongId or implementing IStrongId
        var typeDeclarations = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is TypeDeclarationSyntax typeDecl &&
                                           typeDecl.Modifiers.Any(SyntaxKind.PartialKeyword),
            transform: static (genContext, ct) => GetStrongIdTarget(genContext, ct))
            .Where(static target => target is not null);

        // 3. Register output source generator
        context.RegisterSourceOutput(typeDeclarations, static (sourceContext, target) =>
        {
            // Stryker disable once Statement : Defensive null guard for incremental pipeline
            if (target is null) return;
            GenerateStrongIdSource(sourceContext, target.Value);
        });
    }

    private static StrongIdTarget? GetStrongIdTarget(GeneratorSyntaxContext context, System.Threading.CancellationToken ct)
    {
        var typeDeclaration = (TypeDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(typeDeclaration, ct) is not INamedTypeSymbol typeSymbol)
            return null;

        ITypeSymbol? underlyingType = null;

        // Check attributes: [StrongId(typeof(T))] or [StrongId<T>]
        foreach (var attribute in typeSymbol.GetAttributes())
        {
            var attrClass = attribute.AttributeClass;
            // Stryker disable once Statement : Defensive null check for Roslyn attribute symbol
            if (attrClass is null) continue;

            if (attrClass.Name is "StrongIdAttribute" or "StrongId")
            {
                if (attrClass.IsGenericType && attrClass.TypeArguments.Length == 1)
                {
                    underlyingType = attrClass.TypeArguments[0];
                    break;
                }

                if (attribute.ConstructorArguments.Length == 1 &&
                    attribute.ConstructorArguments[0].Value is ITypeSymbol constructorType)
                {
                    underlyingType = constructorType;
                    break;
                }
            }
        }

        // Check interface implementation: IStrongId<TSelf, TValue>
        if (underlyingType is null)
        {
            foreach (var iface in typeSymbol.AllInterfaces)
            {
                // Stryker disable once Logical, Boolean, Unary : Compiler redundancy between IsGenericType and TypeArguments.Length
                if (iface.IsGenericType &&
                    iface.TypeArguments.Length == 2 &&
                    iface.Name == "IStrongId" &&
                    SymbolEqualityComparer.Default.Equals(iface.TypeArguments[0], typeSymbol))
                {
                    underlyingType = iface.TypeArguments[1];
                    // Stryker disable once Statement : Loop-exit optimization
                    break;
                }
            }
        }

        if (underlyingType is null)
            return null;

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();

        var typeKindKeyword = typeDeclaration switch
        {
            RecordDeclarationSyntax recordDecl when recordDecl.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword) => "readonly record struct",
            RecordDeclarationSyntax => "record class",
            StructDeclarationSyntax => typeDeclaration.Modifiers.Any(SyntaxKind.ReadOnlyKeyword) ? "readonly struct" : "struct",
            ClassDeclarationSyntax => "class",
            // Stryker disable once String : Fallback pattern arm
            _ => "readonly record struct"
        };

        var isRecord = typeDeclaration is RecordDeclarationSyntax;
        var hasValueProperty = typeSymbol.GetMembers("Value").Any();

        return new StrongIdTarget(
            Namespace: ns,
            TypeName: typeSymbol.Name,
            TypeKindKeyword: typeKindKeyword,
            UnderlyingTypeDisplay: underlyingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            UnderlyingTypeName: underlyingType.Name,
            IsRecord: isRecord,
            HasValueProperty: hasValueProperty);
    }

    private static void GenerateStrongIdSource(SourceProductionContext context, StrongIdTarget target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(target.Namespace))
        {
            sb.AppendLine($"namespace {target.Namespace}");
            sb.AppendLine("{");
        }

        var indent = string.IsNullOrEmpty(target.Namespace) ? "" : "    ";

        sb.AppendLine($"{indent}partial {target.TypeKindKeyword} {target.TypeName} : global::EricksonLopez.DomainPrimitives.IStrongId<{target.TypeName}, {target.UnderlyingTypeDisplay}>");
        sb.AppendLine($"{indent}{{");

        // Generate Value property if not present in primary constructor / body
        if (!target.HasValueProperty)
        {
            sb.AppendLine($"{indent}    public {target.UnderlyingTypeDisplay} Value {{ get; init; }}");
            sb.AppendLine();
        }

        // PrimitiveName & IsDefault
        sb.AppendLine($"{indent}    /// <inheritdoc/>");
        sb.AppendLine($"{indent}    public static string PrimitiveName => \"{target.TypeName}\";");
        sb.AppendLine();
        sb.AppendLine($"{indent}    /// <inheritdoc/>");
        sb.AppendLine($"{indent}    public bool IsDefault => global::System.Collections.Generic.EqualityComparer<{target.UnderlyingTypeDisplay}>.Default.Equals(Value, default!);");
        sb.AppendLine();

        // Factory Create
        sb.AppendLine($"{indent}    /// <summary>");
        sb.AppendLine($"{indent}    /// Creates a new instance of <see cref=\"{target.TypeName}\"/>.");
        sb.AppendLine($"{indent}    /// </summary>");
        sb.AppendLine($"{indent}    public static {target.TypeName} Create({target.UnderlyingTypeDisplay} value) => new(value);");
        sb.AppendLine();

        // TryCreate
        sb.AppendLine($"{indent}    /// <inheritdoc/>");
        sb.AppendLine($"{indent}    public static bool TryCreate({target.UnderlyingTypeDisplay} value, out {target.TypeName} result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        result = new(value);");
        sb.AppendLine($"{indent}        validationError = default;");
        sb.AppendLine($"{indent}        return true;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        // If underlying type is Guid, generate New() and Empty
        if (target.UnderlyingTypeName is "Guid")
        {
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// Creates a new <see cref=\"{target.TypeName}\"/> initialized with a sequential UUIDv7 or new Guid.");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    public static {target.TypeName} New() => new(global::System.Guid.NewGuid());");
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// Creates a new, unique identifier.");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    public static {target.TypeName} Create() => new(global::System.Guid.NewGuid());");
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// Gets an empty <see cref=\"{target.TypeName}\"/> instance.");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    public static {target.TypeName} Empty => new(global::System.Guid.Empty);");
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// Gets a value indicating whether this identifier is empty.");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    public bool IsEmpty => Value == global::System.Guid.Empty;");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// Parameterless creation is not supported for non-Guid types.");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    public static {target.TypeName} Create() => throw new global::System.NotSupportedException(\"Parameterless Create() is only supported for Guid-backed strong IDs.\");");
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// Gets an empty <see cref=\"{target.TypeName}\"/> instance.");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    public static {target.TypeName} Empty => new(default!);");
            sb.AppendLine();
        }

        // ToString
        sb.AppendLine($"{indent}    /// <inheritdoc/>");
        sb.AppendLine($"{indent}    public override string ToString() => Value.ToString();");
        sb.AppendLine();

        // Implicit & Explicit conversions
        sb.AppendLine($"{indent}    public static implicit operator {target.UnderlyingTypeDisplay}({target.TypeName} id) => id.Value;");
        sb.AppendLine($"{indent}    public static explicit operator {target.TypeName}({target.UnderlyingTypeDisplay} value) => new(value);");

        // Non-record equality operators
        if (!target.IsRecord)
        {
            sb.AppendLine();
            sb.AppendLine($"{indent}    public bool Equals({target.TypeName} other) => Value.Equals(other.Value);");
            sb.AppendLine($"{indent}    public override bool Equals(object? obj) => obj is {target.TypeName} other && Equals(other);");
            sb.AppendLine($"{indent}    public override int GetHashCode() => Value.GetHashCode();");
            sb.AppendLine($"{indent}    public static bool operator ==({target.TypeName} left, {target.TypeName} right) => left.Equals(right);");
            sb.AppendLine($"{indent}    public static bool operator !=({target.TypeName} left, {target.TypeName} right) => !left.Equals(right);");
        }

        sb.AppendLine($"{indent}}}");

        if (!string.IsNullOrEmpty(target.Namespace))
        {
            sb.AppendLine("}");
        }

        context.AddSource($"{target.TypeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private readonly struct StrongIdTarget : IEquatable<StrongIdTarget>
    {
        public string Namespace { get; }
        public string TypeName { get; }
        public string TypeKindKeyword { get; }
        public string UnderlyingTypeDisplay { get; }
        public string UnderlyingTypeName { get; }
        public bool IsRecord { get; }
        public bool HasValueProperty { get; }

        public StrongIdTarget(
            string Namespace,
            string TypeName,
            string TypeKindKeyword,
            string UnderlyingTypeDisplay,
            string UnderlyingTypeName,
            bool IsRecord,
            bool HasValueProperty)
        {
            this.Namespace = Namespace;
            this.TypeName = TypeName;
            this.TypeKindKeyword = TypeKindKeyword;
            this.UnderlyingTypeDisplay = UnderlyingTypeDisplay;
            this.UnderlyingTypeName = UnderlyingTypeName;
            this.IsRecord = IsRecord;
            this.HasValueProperty = HasValueProperty;
        }

        public bool Equals(StrongIdTarget other) =>
            Namespace == other.Namespace &&
            TypeName == other.TypeName &&
            TypeKindKeyword == other.TypeKindKeyword &&
            UnderlyingTypeDisplay == other.UnderlyingTypeDisplay &&
            UnderlyingTypeName == other.UnderlyingTypeName &&
            IsRecord == other.IsRecord &&
            HasValueProperty == other.HasValueProperty;

        public override bool Equals(object? obj) => obj is StrongIdTarget other && Equals(other);
        public override int GetHashCode() => (Namespace, TypeName, UnderlyingTypeDisplay).GetHashCode();
    }
}
