// Copyright © Erickson Lopez. MIT License.

namespace EricksonLopez.SharedKernel.Persistence;

using System;

/// <summary>
/// Specifies the database column that a property is mapped to.
/// </summary>
[AttributeUsage(AttributeTargets.Property, Inherited = false)]
public sealed class ColumnAttribute : Attribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ColumnAttribute"/> class with the specified column name.
    /// </summary>
    /// <param name="name">The name of the database column.</param>
    public ColumnAttribute(string name)
    {
        Name = name;
    }

    /// <summary>
    /// Gets the name of the column.
    /// </summary>
    public string Name { get; }

    /// <summary>
    /// Gets or sets whether this column is part of the primary key.
    /// </summary>
    public bool IsPrimaryKey { get; set; }

    /// <summary>
    /// Gets or sets whether this column's value is generated by the database (e.g., identity or default expression).
    /// </summary>
    public bool IsDatabaseGenerated { get; set; }
}
