// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using AwesomeAssertions;
using EricksonLopez.Events.Contracts;
using EricksonLopez.Events.Identifiers;
using EricksonLopez.SharedKernel;
using Xunit;

#pragma warning disable CS0618 // Tested for backward compatibility
#pragma warning disable CS8602 // Deliberately testing null passing to equality methods

namespace EricksonLopez.SharedKernel.UnitTests;

/// <summary>
/// Comprehensive verification tests verifying all remediations from the forensic Mega-Audit.
/// </summary>
public sealed class RemediationVerificationTests
{
    private sealed record TestDomainEvent(string Data) : DomainEvent;

    private sealed class OrderAggregate : AggregateRoot<Guid>
    {
        public OrderAggregate(Guid id) : base(id) { }

        public void EmitEvent(DomainEvent evt) => RaiseDomainEvent(evt);
    }

    #region FND-01: DomainEvents Tamper Resistance

    [Fact]
    public void AggregateRoot_DomainEvents_CannotBeCastToMutableIList_ThwartingTampering()
    {
        // Arrange
        var aggregate = new OrderAggregate(Guid.NewGuid());
        aggregate.EmitEvent(new TestDomainEvent("Original Event"));

        // Act
        var events = aggregate.DomainEvents;

        // Assert: ReadOnlyDomainEventList does NOT implement IList<IDomainEvent> or IList
        (events is IList<IDomainEvent>).Should().BeFalse(
            because: "DomainEvents must return a truly immutable list that cannot be downcast to IList<IDomainEvent>");

        (events is System.Collections.IList).Should().BeFalse(
            because: "DomainEvents must not implement non-generic IList");

        // Action cast to IList<IDomainEvent> throws InvalidCastException
        Action castAction = () => { var _ = (IList<IDomainEvent>)events; };
        castAction.Should().Throw<InvalidCastException>();

        // Drained events are unaltered
        var drained = aggregate.DrainDomainEvents();
        drained.Should().HaveCount(1);
        drained[0].Should().BeOfType<TestDomainEvent>();
    }

    [Fact]
    public void AggregateRoot_DrainDomainEvents_CannotBeCastToMutableIList()
    {
        // Arrange
        var aggregate = new OrderAggregate(Guid.NewGuid());
        aggregate.EmitEvent(new TestDomainEvent("Drained Event"));

        // Act
        var drained = aggregate.DrainDomainEvents();

        // Assert
        (drained is IList<IDomainEvent>).Should().BeFalse();
        Action castAction = () => { var _ = (IList<IDomainEvent>)drained; };
        castAction.Should().Throw<InvalidCastException>();
    }

    #endregion



    #region FND-02: Class-Based Strong ID Null Safety

    // Simulated non-record class strong ID as generated by StrongIdGenerator
    public class CustomerId : IEquatable<CustomerId>
    {
        public Guid Value { get; init; }

        public CustomerId(Guid value) => Value = value;

        public bool Equals(CustomerId? other) => other is not null && Value.Equals(other.Value);

        public override bool Equals(object? obj) => obj is CustomerId other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(CustomerId? left, CustomerId? right) =>
            ReferenceEquals(left, right) || (left is not null && left.Equals(right));

        public static bool operator !=(CustomerId? left, CustomerId? right) => !(left == right);
    }

    [Fact]
    public void ClassBasedStrongId_EqualsNull_ReturnsFalse_WithoutThrowing()
    {
        var id = new CustomerId(Guid.NewGuid());

        bool equalsStrongNull = id.Equals((CustomerId?)null);
        equalsStrongNull.Should().BeFalse(because: "Equals(null) must return false per .NET contracts");

        object? nullObj = null;
        bool equalsObjectNull = id.Equals(nullObj);
        equalsObjectNull.Should().BeFalse();
    }

    [Fact]
    public void ClassBasedStrongId_OperatorEqualityWithNull_ReturnsFalse_WithoutThrowing()
    {
        CustomerId? nullId = null;
        var validId = new CustomerId(Guid.NewGuid());

        bool nullEqualsValid = nullId == validId;
        nullEqualsValid.Should().BeFalse();

        bool validEqualsNull = validId == nullId;
        validEqualsNull.Should().BeFalse();

        bool nullNotEqualsValid = nullId != validId;
        nullNotEqualsValid.Should().BeTrue();

        bool validNotEqualsNull = validId != nullId;
        validNotEqualsNull.Should().BeTrue();
    }

    #endregion

    #region FND-03: IDomainEventDispatcher Sync-Over-Async Elimination

    private sealed class StubAsyncOnlyDispatcher : IDomainEventDispatcher
    {
        public ValueTask DispatchAsync(IReadOnlyList<IDomainEvent> domainEvents, CancellationToken cancellationToken = default)
            => ValueTask.CompletedTask;
    }

    [Fact]
    public void IDomainEventDispatcher_DefaultDispatch_ThrowsNotSupportedException()
    {
        IDomainEventDispatcher dispatcher = new StubAsyncOnlyDispatcher();
        var events = new IDomainEvent[] { new TestDomainEvent("Test") };

        Action act = () => dispatcher.Dispatch(events);

        act.Should().Throw<NotSupportedException>(
            because: "Default Dispatch must throw NotSupportedException to prevent sync-over-async threadpool starvation and deadlocks");
    }

    #endregion

    #region FND-08: Obsolete DomainEvent Aliases

    [Fact]
    public void DomainEvent_EventIdAndOccurredOn_AreNotMarkedObsolete()
    {
        var eventIdProp = typeof(DomainEvent).GetProperty("EventId");
        var occurredOnProp = typeof(DomainEvent).GetProperty("OccurredOn");

        eventIdProp.Should().NotBeNull();
        occurredOnProp.Should().NotBeNull();

        var eventIdObsolete = eventIdProp!.GetCustomAttribute<ObsoleteAttribute>();
        var occurredOnObsolete = occurredOnProp!.GetCustomAttribute<ObsoleteAttribute>();

        eventIdObsolete.Should().BeNull();
        occurredOnObsolete.Should().BeNull();
    }

    #endregion

    #region PERF-01: PropertyMetadata Zero-Boxing Accessors

    private sealed class EntityForPerf
    {
        public int Id { get; set; }
    }

    [Fact]
    public void PropertyMetadata_GetValue_WithStronglyTypedGetter_IncursZeroAllocations()
    {
        var entity = new EntityForPerf { Id = 42 };
        Func<EntityForPerf, int> typedGetter = e => e.Id;

        var prop = new EricksonLopez.SharedKernel.Persistence.PropertyMetadata(
            ClrName: nameof(EntityForPerf.Id),
            ClrType: typeof(int),
            ColumnName: "id",
            DatabaseType: "integer",
            IsKey: true,
            IsNullable: false,
            IsAuditColumn: false,
            IsSoftDeleteColumn: false,
            IsTenantColumn: false,
            IsConcurrencyToken: false,
            Getter: obj => ((EntityForPerf)obj).Id,
            Setter: null)
        {
            StronglyTypedGetter = typedGetter
        };

        // Warm up JIT
        _ = prop.GetValue<EntityForPerf, int>(entity);

        long bytesBefore = GC.GetAllocatedBytesForCurrentThread();
        for (int i = 0; i < 10_000; i++)
        {
            var val = prop.GetValue<EntityForPerf, int>(entity);
            _ = val + i;
        }
        long bytesAfter = GC.GetAllocatedBytesForCurrentThread();
        long totalAllocated = bytesAfter - bytesBefore;

        totalAllocated.Should().Be(0, because: "Strongly-typed GetValue on PropertyMetadata must execute with zero heap boxing allocations.");
    }

    #endregion

    #region FND-SK-003: Blank & Whitespace String Identity Rejection

    private sealed class UserEntity : Entity<string>
    {
        public UserEntity(string id) : base(id) { }
    }

    [Theory]
    [InlineData("")]
    [InlineData(" ")]
    [InlineData("   ")]
    [InlineData("\t")]
    [InlineData("\n")]
    [InlineData("\r\n")]
    public void Entity_WithStringId_RejectsEmptyAndWhitespace(string invalidId)
    {
        Action act = () => { _ = new UserEntity(invalidId); };
        act.Should().Throw<ArgumentException>()
            .WithMessage("*Entity identity cannot be empty or whitespace.*");
    }

    [Fact]
    public void Entity_WithStringId_AcceptsValidTrimmedString()
    {
        var entity = new UserEntity("usr_12345");
        entity.Id.Should().Be("usr_12345");
    }

    #endregion

    #region FND-SK-004: Zero [Obsolete] Policy in Persistence Attributes

    [Fact]
    public void PersistenceAttributes_HaveZeroObsoleteAttributes()
    {
        typeof(EricksonLopez.SharedKernel.Persistence.AuditAttribute)
            .GetCustomAttribute<ObsoleteAttribute>().Should().BeNull();

        typeof(EricksonLopez.SharedKernel.Persistence.AuditFieldType)
            .GetCustomAttribute<ObsoleteAttribute>().Should().BeNull();

        typeof(EricksonLopez.SharedKernel.Persistence.TenantScopedAttribute)
            .GetCustomAttribute<ObsoleteAttribute>().Should().BeNull();

        typeof(EricksonLopez.SharedKernel.Persistence.TableAttribute)
            .GetCustomAttribute<ObsoleteAttribute>().Should().BeNull();

        typeof(EricksonLopez.SharedKernel.Persistence.ColumnAttribute)
            .GetCustomAttribute<ObsoleteAttribute>().Should().BeNull();
    }

    #endregion

    #region FND-SK-005: IHasDomainEvents Contract & Requeue

    private sealed class CustomHasDomainEvents : IHasDomainEvents
    {
        private readonly List<IDomainEvent> _events = [];

        public IReadOnlyList<IDomainEvent> DomainEvents => _events;

        public void Add(IDomainEvent evt) => _events.Add(evt);

        public IReadOnlyList<IDomainEvent> DrainDomainEvents()
        {
            var copy = _events.ToArray();
            _events.Clear();
            return copy;
        }

        public void RequeueDomainEvents(IEnumerable<IDomainEvent> events)
        {
            _events.InsertRange(0, events);
        }
    }

    [Fact]
    public void IHasDomainEvents_DomainEvents_IsAbstractProperty()
    {
        var prop = typeof(IHasDomainEvents).GetProperty(nameof(IHasDomainEvents.DomainEvents));
        prop.Should().NotBeNull();
        prop!.GetMethod.Should().NotBeNull();
        prop.GetMethod!.IsAbstract.Should().BeTrue(because: "DomainEvents must be an abstract interface property per FND-SK-005.");
    }

    [Fact]
    public void AggregateRoot_RequeueDomainEvents_RestoresEventsInCorrectOrder()
    {
        var aggregate = new OrderAggregate(Guid.NewGuid());
        var evt1 = new TestDomainEvent("Event 1");
        var evt2 = new TestDomainEvent("Event 2");

        aggregate.EmitEvent(evt1);
        aggregate.EmitEvent(evt2);

        var drained = aggregate.DrainDomainEvents();
        drained.Should().HaveCount(2);
        aggregate.PendingDomainEventsCount.Should().Be(0);

        // Act: Requeue
        aggregate.RequeueDomainEvents(drained);

        // Assert: Events restored in order
        aggregate.PendingDomainEventsCount.Should().Be(2);
        aggregate.DomainEvents.Should().HaveCount(2);
        aggregate.DomainEvents[0].Should().BeSameAs(evt1);
        aggregate.DomainEvents[1].Should().BeSameAs(evt2);
    }

    #endregion

    #region FND-SK-009: DomainEvent Identity Equality

    [Fact]
    public void DomainEventIdentityEqualityComparer_ComparesStrictlyById()
    {
        var id = EventId.New();
        var evt1 = new ExplicitEvent(id, DateTimeOffset.UtcNow, "Payload A");
        var evt2 = new ExplicitEvent(id, DateTimeOffset.UtcNow.AddMinutes(5), "Payload B");

        // Object equality (record memberwise comparison)
        (evt1 == evt2).Should().BeFalse(because: "Record equality compares all members.");

        // Identity equality comparison
        DomainEventIdentityEqualityComparer.Instance.Equals(evt1, evt2).Should().BeTrue(
            because: "DomainEventIdentityEqualityComparer must evaluate equality based strictly on EventId per FND-SK-009.");
        DomainEventIdentityEqualityComparer.Instance.GetHashCode(evt1).Should().Be(
            DomainEventIdentityEqualityComparer.Instance.GetHashCode(evt2));
    }

    private sealed record ExplicitEvent : DomainEvent
    {
        public string Payload { get; }

        public ExplicitEvent(EventId id, DateTimeOffset occurredAt, string payload)
            : base(id, occurredAt)
        {
            Payload = payload;
        }
    }

    #endregion
}
