name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    uses: ericksonlopezf/dotnet-shared-kernel/.github/workflows/dotnet-build-test.yml@main
    with:
      artifact-name: test-results
    secrets:
      SNK_KEY: ${{ secrets.SNK_KEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  aot-smoke-test:
    uses: ericksonlopezf/dotnet-shared-kernel/.github/workflows/aot-smoke-test.yml@main
    secrets:
      SNK_KEY: ${{ secrets.SNK_KEY }}
